-- Azuregos (Vanilla world bosses, v0.5.2)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/Azuregos.tga (Wowhead zone 16) + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (WorldBossesClassic + IP zone_azshara.sql sinew), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/zone_azshara.sql + AC boss_azuregos.cpp smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    id = "azuregos",
    name = "Azuregos",
    level = "60+",
    minLevel = "60",
    location = "Azshara",
    tag = "World Boss",
    art = SDJ.MAPS .. "Azuregos",
    crop = {0.0, 1.0, 0.0, 1.0},
    artFallback = SDJ.MAPS .. "Azuregos",
    fallbackCrop = {0.0, 1.0, 0.0, 1.0},
    maps = {
        {
            name = "Azuregos (Azshara)",
            texture = SDJ.MAPS .. "Azuregos",
            coords = {0, 1, 0, 1},
            legend = {
                {"", "World Boss — level 63", "blue"},
                {"", "Spawn (AC): map 1 / Azshara world (2622.22, −5977.93, 100.76)"},
                {"", "spawntimesecs 868400 ≈ 10.05 days"},
                {"1", "Azuregos (Bay of Storms / south Azshara coast)"},
            },
            credit = "Zone map art (c) Blizzard via Wowhead (wow.zamimg.com); markers from AzerothCore / IP spawn coordinates zone 16",
        },
    },
    trash = {
        mobs = {},
        loot = {},
    },
    bosses = {
        {
            name = "Azuregos",
            id = 6109,
            level = "63 Boss",
            portrait = P .. "Azuregos",
            abilities = {
                {spell = 21097, name = "Manastorm", tag = "MANA", desc = "Mana burn AoE on a random target — casters watch mana."},
                {spell = 21147, name = "Arcane Vacuum", tag = "TELEPORT", desc = "Pulls/teleports nearby players (script also uses Arcane Vacuum TP 21150)."},
                {spell = 22067, name = "Reflection", tag = "REFLECT", desc = "Reflects spells while active — stop casting into Reflect."},
                {spell = 21098, name = "Chill", tag = "FROST", desc = "Frost slow / chill on the tank."},
                {spell = 21099, name = "Frost Breath", tag = "FROST", desc = "Frost breath cone."},
                {spell = 19983, name = "Cleave", tag = "CLEAVE", desc = "Frontal cleave."},
                {spell = 23182, name = "Mark of Frost", tag = "WIPE", desc = "Applied on death; returning while marked triggers Aura of Frost."},
            },
            mechanics = {
                "Outdoor Azshara world boss (creature 6109). Bring a full raid; frost resistance helps.",
                "Manastorm (21097): drains mana — drinkers and mana pots ready.",
                "Arcane Vacuum (21147 / 21150): teleports the raid onto him — stay stacked for heals after the pull-in.",
                "Reflection (22067): stop DPS casts while Reflect is up.",
                "Mark of Frost (23182): dying to him marks you; re-engaging too soon applies Aura of Frost — wait out the mark.",
                "IP: Mature Blue Dragon Sinew (18704) Chance set to 100% in zone_azshara.sql (AtlasLoot listed 51.56%).",
                "Respawn: creature.spawntimesecs = 868400 (~10 days) on AzerothCore.",
            },
            loot = {
                {id = 18541, name = "Puissant Cape", slot = "Back", quality = 4, icon = "inv_misc_cape_06", rate = "11.71%"},
                {id = 18208, name = "Drape of Benediction", slot = "Back", quality = 4, icon = "inv_misc_cape_04", rate = "11.22%"},
                {id = 19132, name = "Crystal Adorned Crown", slot = "Head, Cloth", quality = 4, icon = "inv_crown_01", rate = "13.54%"},
                {id = 18545, name = "Leggings of Arcane Supremacy", slot = "Legs, Cloth", quality = 4, icon = "inv_pants_08", rate = "16.39% "},
                {id = 19131, name = "Snowblind Shoes", slot = "Feet, Cloth", quality = 4, icon = "inv_boots_cloth_14", rate = "12.23%"},
                {id = 18547, name = "Unmelting Ice Girdle", slot = "Waist, Plate", quality = 4, icon = "inv_belt_31", rate = "12.93%"},
                {id = 17070, name = "Fang of the Mystics", slot = "Main Hand, Dagger", quality = 4, icon = "inv_weapon_shortblade_06", rate = "13.64%"},
                {id = 18202, name = "Eskhandar's Left Claw", slot = "Off Hand, Fist Weapon", quality = 4, icon = "inv_misc_monsterclaw_04", rate = "11.76%"},
                {id = 18542, name = "Typhoon", slot = "Two-Hand, Sword", quality = 4, icon = "inv_sword_41", rate = "16.89%"},
                {id = 19130, name = "Cold Snap", slot = "Ranged, Wand", quality = 4, icon = "inv_wand_01", rate = "11.89%"},
                {
                    id = 18704,
                    name = "Mature Blue Dragon Sinew",
                    slot = "Quest Item",
                    quality = 4,
                    icon = "inv_misc_bandage_04",
                    rate = "100%",
                    note = "Hunter quest item for Ancient Sinew Wrapped Lamina (7634). Individual Progression rate 100% (AtlasLoot 51.56%).",
                },
            },
        },
    },
    quests = {
        {
            id = 7632,
            name = "The Ancient Leaf",
            faction = "Both",
            level = 60,
            minLevel = 60,
            objective = "Turn in An Ancient Leaf (from Felwood / emerald dragon chain context) to unlock the Ancient Leaf hunter book path.",
            notes = "Leads toward Ancient Sinew Wrapped Lamina with Mature Blue Dragon Sinew from Azuregos.",
        },
        {
            id = 7634,
            name = "Ancient Sinew Wrapped Lamina",
            faction = "Both",
            level = 60,
            minLevel = 60,
            objective = "Provide Mature Blue Dragon Sinew (18704) and related materials for Ancient Sinew Wrapped Lamina.",
            notes = "Sinew is 100% from Azuregos on this server (IP).",
        },
        {
            id = 8575,
            name = "Azuregos's Magical Ledger",
            faction = "Both",
            level = 60,
            minLevel = 60,
            objective = "Deliver Azuregos's Magical Ledger to Narain Soothfancy in Tanaris.",
            notes = "Azuregos Magical Ledger — part of the Blue Scepter / Narain Soothing Turtle Bisque chain (AQ gates).",
        },
    },
    preparation = {
        {
            title = "Location / respawn",
            lines = {
                "Azshara — Bay of Storms / southern coastal shelf. Server spawn: (2622.22, −5977.93, 100.76) on Kalimdor (map 1).",
                "Respawn: spawntimesecs 868400 (~10.05 days) from AzerothCore creature row.",
                "Level 63 Boss (creature_template / IP). Not phased behind an IP stage (unlike Emerald Dragons).",
            },
        },
        {
            title = "Mechanics focus",
            lines = {
                "Frost Resistance for Chill / Frost Breath.",
                "Mana management for Manastorm; interrupt discipline for Reflection windows.",
                "Do not re-pull while Mark of Frost is still on you.",
            },
        },
        {
            title = "Resistance / consumables",
            lines = {
                "Frost Resistance gear and Greater Frost Protection potions.",
                "Major Mana / Mana potions for casters; standard raid flasks/food.",
            },
        },
    },
})
