-- Lord Kazzak (Vanilla world bosses, v0.5.2)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/LordKazzak.tga (Wowhead zone 4) + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (IP boss_lord_kazzak.sql ref 60000), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/boss_lord_kazzak.sql / vanillaScripts/boss_lord_kazzak.cpp smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    id = "kazzak",
    name = "Lord Kazzak",
    level = "60+",
    minLevel = "60",
    location = "Blasted Lands",
    tag = "World Boss",
    art = SDJ.MAPS .. "LordKazzak",
    crop = {0.0, 1.0, 0.0, 1.0},
    artFallback = SDJ.MAPS .. "LordKazzak",
    fallbackCrop = {0.0, 1.0, 0.0, 1.0},
    maps = {
        {
            name = "Lord Kazzak (Blasted Lands)",
            texture = SDJ.MAPS .. "LordKazzak",
            coords = {0, 1, 0, 1},
            legend = {
                {"", "World Boss — level 63", "blue"},
                {"", "IP restored spawn guid 156950: (−12226.8, −2433.57, 1.765) map 0"},
                {
                    "",
                    "Template spawntimesecs 604800 (7d); on death script sets urand(2–3 days)",
                },
                {"1", "Lord Kazzak — Tainted Scar"},
            },
            credit = "Zone map art (c) Blizzard via Wowhead (wow.zamimg.com); markers from AzerothCore / IP spawn coordinates zone 4",
        },
    },
    trash = {
        mobs = {},
        loot = {},
    },
    bosses = {
        {
            name = "Lord Kazzak",
            id = 12397,
            level = "63 Boss",
            portrait = P .. "LordKazzak",
            abilities = {
                {spell = 21341, name = "Shadowbolt Volley", tag = "SHADOW", desc = "Shadow AoE volley on the tank/raid."},
                {spell = 16044, name = "Cleave", tag = "CLEAVE", desc = "Frontal cleave."},
                {spell = 15588, name = "Thunderclap", tag = "SLOW", desc = "AoE slow / thunderclap."},
                {spell = 21066, name = "Void Bolt", tag = "SHADOW", desc = "Single-target void bolt."},
                {spell = 21056, name = "Mark of Kazzak", tag = "MANA", desc = "Mana leech on a random mana user; if mana ≤50, Mark of Kazzak damage detonates."},
                {spell = 21063, name = "Twisted Reflection", tag = "MAGIC", desc = "Heal absorb / twisted reflection on a random player — dispel/kill priority."},
                {spell = 21054, name = "Capture Soul", tag = "HEAL", desc = "Cast on killing a player — heals Kazzak."},
            },
            mechanics = {
                "Restored by Individual Progression boss_lord_kazzak.sql + vanillaScripts/boss_lord_kazzak.cpp (ScriptName boss_lord_kazzak).",
                "Mark of Kazzak (21056): put on a random mana class (not tank); drains mana — if they hit ≤50 mana the mark explodes (21058). Keep marked players topped on mana or dispel according to your raid plan.",
                "Twisted Reflection (21063): random player; heals Kazzak from damage taken by the reflect — dispel or stop damaging the reflect target as your strat requires.",
                "Capture Soul on player kills — dead players feed him. Avoid unnecessary deaths.",
                "EVENT_BERSERK at 180 seconds: supreme mode — Shadowbolt Volley spam (~1s). Kill before 3:00 or be ready for the enrage timer as scripted.",
                "Note: EVENT_ENRAGE (Frenzy 21340) exists in the IP script enum but is not ScheduleEvent’d on pull — only the 180s Berserk/supreme path is armed.",
                "Respawn: JustDied sets SetRespawnTime(urand(2*DAY, 3*DAY)); template also has spawntimesecs 604800.",
                "Highlord Kruul (18338) exists as a template tweak in TBC SQL but has no creature spawn in AC/IP — omitted.",
            },
            loot = {
                {
                    id = 17111,
                    name = "Blazefury Medallion",
                    slot = "Neck",
                    quality = 4,
                    icon = "inv_jewelry_talisman_01",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 17112,
                    name = "Empyrean Demolisher",
                    slot = "One-Hand, Mace",
                    quality = 4,
                    icon = "inv_hammer_05",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 17113,
                    name = "Amberseal Keeper",
                    slot = "Two-Hand, Staff",
                    quality = 4,
                    icon = "inv_staff_goldfeathered_01",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 18204,
                    name = "Eskhandar's Pelt",
                    slot = "Back",
                    quality = 4,
                    icon = "inv_misc_cape_07",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 18543,
                    name = "Ring of Entropy",
                    slot = "Finger",
                    quality = 4,
                    icon = "inv_jewelry_ring_20",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 18544,
                    name = "Doomhide Gauntlets",
                    slot = "Hands, Leather",
                    quality = 4,
                    icon = "inv_gauntlets_22",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 18546,
                    name = "Infernal Headcage",
                    slot = "Head, Mail",
                    quality = 4,
                    icon = "inv_helmet_18",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 19133,
                    name = "Fel Infused Leggings",
                    slot = "Legs, Cloth",
                    quality = 4,
                    icon = "inv_pants_06",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 19134,
                    name = "Flayed Doomguard Belt",
                    slot = "Waist, Leather",
                    quality = 4,
                    icon = "inv_belt_16",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
                {
                    id = 19135,
                    name = "Blacklight Bracer",
                    slot = "Wrist, Cloth",
                    quality = 4,
                    icon = "inv_bracer_07",
                    rate = "~20% (2 rolls of 1/10)",
                    note = "Individual Progression reference_loot_template 60000 (equal weight, GroupId 1); creature rolls 2 items (MinCount/MaxCount 2).",
                },
            },
        },
    },
    quests = {},
    preparation = {
        {
            title = "Location / respawn",
            lines = {
                "Blasted Lands — Tainted Scar. IP spawn (−12226.8, −2433.57, 1.765) map Eastern Kingdoms.",
                "On death: script respawn urand(2–3 days). Template spawntimesecs 604800 (~7 days) also present on the row.",
                "Level 63 Boss (IP vanilla_creatures / boss_lord_kazzak.sql).",
            },
        },
        {
            title = "Enrage / supreme timer",
            lines = {
                "180-second Berserk (EVENT_BERSERK): enters supreme mode and spams Shadowbolt Volley.",
                "Plan for a sub-3-minute kill or heavy shadow mitigation after the timer.",
            },
        },
        {
            title = "Resistance / consumables",
            lines = {
                "Shadow Resistance gear and Greater Shadow Protection potions strongly recommended.",
                "Mana users: bring Major Mana; Mark of Kazzak punishes empty mana bars.",
                "Standard raid flasks/food; no named bot consumables profile (see Bot Consumables).",
            },
        },
    },
})
