-- Maraudon - Orange Side (Vanilla batch 5, v0.3.5)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/Maraudon.blp + MaraudonEnt.blp + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (Maraudon1/2), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/dungeon_maraudon.sql / instance_maraudon.cpp smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    location = "Desolace",
    tag = "Dungeon",
    art = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenMaraudon",
    artFallback = SDJ.MAPS .. "Maraudon",
    crop = {0.04, 0.96, 0.29, 0.73},
    fallbackCrop = {0.0, 1.0, 0.25, 0.7},
    minLevel = "30",
    id = "mara_o",
    name = "Maraudon - Orange Side",
    level = "42-48",
    maps = {
        {
            name = "Maraudon (Orange: Foulspore Cavern)",
            texture = SDJ.MAPS .. "Maraudon",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance (Orange)", "blue"},
                {"1", "Veng <The Fifth Khan>"},
                {"2", "Noxxion"},
                {"3", "Razorlash"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL. Shared map of all three wings; only this wing's markers are listed.",
        },
        {
            name = "Maraudon (Entrance)",
            texture = SDJ.MAPS .. "MaraudonEnt",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"", "The Nameless Prophet (Amulet of Spirits)"},
                {"B", "Maraudon (Purple)", "blue"},
                {"C", "Maraudon (Orange)", "blue"},
                {"D", "Maraudon (Portal) - Scepter of Celebras", "blue"},
                {"1", "Kolk <The First Khan>"},
                {"2", "Gelk <The Second Khan>"},
                {"3", "Magra <The Third Khan>"},
                {"4", "Cavindra"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
    },
    trash = {
        mobs = {
            {
                name = "Constrictor Vine",
                npc = 12220,
                level = "45-46 Elite",
                priority = 2,
                abilities = {
                    {spell = 11922, name = "Entangling Roots", tag = "ROOT", desc = "Roots a player and deals Nature damage."},
                },
                note = "",
            },
            {
                name = "Creeping Sludge",
                npc = 12222,
                level = "45-46 Elite",
                priority = 2,
                abilities = {
                    {spell = 21070, name = "Noxious Cloud", tag = "AOE", desc = "Poison cloud in melee range and when it dies."},
                },
                note = "Move out of the cloud when it dies.",
            },
            {
                name = "Barbed Lasher",
                npc = 12219,
                level = "44-45 Elite",
                priority = 2,
                abilities = {
                    {spell = 21749, name = "Thorn Volley", tag = "AOE", desc = "Damages and knocks down nearby players."},
                },
                note = "",
            },
            {
                name = "Vile Larva",
                npc = 12218,
                level = "45-47",
                priority = 3,
                abilities = {
                    {spell = 21069, name = "Larva Goo", tag = "POISON", desc = "Poisons nearby players."},
                },
                note = "Not elite; come in large groups.",
            },
            {
                name = "Spewed Larva",
                npc = 13533,
                level = "45-47 Elite",
                priority = 3,
                abilities = {
                    {spell = 5413, name = "Noxious Catalyst", tag = "DEBUFF", desc = "Lowers Nature resistance."},
                },
                note = "",
            },
            {
                name = "Celebrian Dryad",
                npc = 11793,
                level = "45-46 Elite",
                priority = 2,
                abilities = {
                    {spell = 16000, name = "Throw", desc = "Ranged attack."},
                    {spell = 17201, name = "Dispel Magic", desc = "Removes a debuff from an ally."},
                    {spell = 8601, name = "Slowing Poison", tag = "POISON", desc = "Melee hits can slow you."},
                },
                note = "",
            },
            {
                name = "Deeprot Stomper",
                npc = 13141,
                level = "43-44 Elite",
                priority = 2,
                abilities = {
                    {spell = 13446, name = "Strike", desc = "Heavy melee hit."},
                    {spell = 11876, name = "War Stomp", tag = "STUN", desc = "Stuns and knocks back nearby players."},
                },
                note = "",
            },
            {
                name = "Poison Sprite",
                npc = 12216,
                level = "42-43",
                priority = 3,
                abilities = {
                    {spell = 21067, name = "Poison Bolt", tag = "POISON", desc = "Nature damage over time."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Not elite.",
            },
            {
                name = "Noxxious Scion",
                npc = 13696,
                level = "45-46",
                priority = 3,
                abilities = {
                    {spell = 21068, name = "Corruption", tag = "DOT", desc = "Shadow damage over time."},
                    {spell = 5413, name = "Noxious Catalyst", tag = "DEBUFF", desc = "Lowers Nature resistance."},
                },
                note = "Emerges from Vylestem Vines when you use the Filled Cerulean Vial (Vyletongue Corruption).",
            },
        },
        loot = {
            {
                id = 17684,
                name = "Theradric Crystal Carving",
                slot = "Quest Item",
                quality = 1,
                icon = "inv_jewelry_talisman_07",
                rate = "80%",
                note = "Twisted Evils (7028). AzerothCore: 80% from most Maraudon mobs and bosses.",
            },
        },
        lootNote = "AtlasLoot has no Maraudon trash table; quest drop from the AzerothCore loot tables.",
    },
    bosses = {
        {
            name = "Veng",
            npc = 13738,
            level = "47 Elite",
            optional = true,
            portrait = P .. "Veng",
            summary = "The Fifth Khan [1]. Appears as the Spirit of Veng; the Amulet of Spirits makes him manifest (The Pariah's Instructions).",
            abilities = {
                {spell = 15547, name = "Shoot", desc = "Ranged attack."},
                {spell = 14443, name = "Multi-Shot", tag = "AOE", desc = "Hits the target and nearby players."},
            },
            mechanics = {
                "Use the Amulet of Spirits (from The Nameless Prophet) on the Spirit of Veng.",
                "Abilities are from the AzerothCore script of the Spirit of Veng.",
            },
            loot = {
                {
                    id = 17765,
                    name = "Gem of the Fifth Khan",
                    slot = "Quest Item",
                    quality = 1,
                    icon = "inv_misc_gem_opal_01",
                    rate = "100%",
                    note = "The Pariah's Instructions (7067).",
                },
            },
        },
        {
            name = "Noxxion",
            npc = 13282,
            level = "48 Elite",
            portrait = P .. "Noxxion",
            summary = "Poison elemental [2]. Drops the Celebrian Rod.",
            abilities = {
                {spell = 21687, name = "Toxic Volley", desc = "Nature damage to a player."},
                {spell = 10966, name = "Uppercut", desc = "Knocks a player back."},
                {
                    spell = 21707,
                    name = "Summon Noxxion's Spawns",
                    tag = "SUMMON",
                    desc = "At 50% health he becomes untargetable and summons 5 Noxxion Spawns until they die.",
                },
            },
            mechanics = {
                "At 50% kill the Noxxion Spawns; he returns when they are dead.",
                "Cure poison.",
            },
            loot = {
                {id = 17746, name = "Noxxion's Shackles", slot = "Wrist, Plate", quality = 3, icon = "inv_bracer_06", rate = "32.50%"},
                {id = 17744, name = "Heart of Noxxion", slot = "Trinket", quality = 3, icon = "inv_misc_gem_pearl_06", rate = "30.35%"},
                {id = 17745, name = "Noxious Shooter", slot = "Ranged, Wand", quality = 3, icon = "inv_wand_04", rate = "17.53%"},
                {id = 17702, name = "Celebrian Rod", slot = "Quest Item", quality = 1, icon = "inv_staff_19", rate = "100%", note = "Legends of Maraudon (7044)."},
            },
        },
        {
            name = "Razorlash",
            npc = 12258,
            level = "48 Elite",
            portrait = P .. "Razorlash",
            summary = "Thorned lasher [3].",
            abilities = {
                {spell = 40504, name = "Cleave", desc = "Hits up to 3 targets in front."},
                {spell = 15976, name = "Puncture", tag = "DOT", desc = "Bleed on the tank."},
                {spell = 3391, name = "Thrash", desc = "Extra attacks."},
                {spell = 21911, name = "Puncture (passive)", desc = "Melee hits can cause a bleed."},
            },
            mechanics = {"Only the tank in front."},
            loot = {
                {id = 17750, name = "Chloromesh Girdle", slot = "Waist, Cloth", quality = 3, icon = "inv_belt_25", rate = "22.93%"},
                {id = 17748, name = "Vinerot Sandals", slot = "Feet, Cloth", quality = 3, icon = "inv_boots_05", rate = "20.60%"},
                {id = 17749, name = "Phytoskin Spaulders", slot = "Shoulder, Leather", quality = 3, icon = "inv_shoulder_06", rate = "22.09%"},
                {id = 17751, name = "Brusslehide Leggings", slot = "Legs, Leather", quality = 3, icon = "inv_pants_05", rate = "21.65%"},
            },
        },
    },
    quests = {
        {
            id = 7041,
            name = "Vyletongue Corruption",
            faction = "Alliance",
            level = 47,
            minLevel = 41,
            prerequisites = "None. Starts with a Coated Cerulean Vial.",
            requiredItems = {
                {id = 17696, name = "Filled Cerulean Vial", where = "Fill the vial at an orange crystal pool outside the Orange side"},
            },
            where = "Use the vial on Vylestem Vines (Orange and Purple wings) and kill the 8 Noxxious Scions that emerge.",
            turnin = "Talendria",
            turninLocation = "Desolace - Nijel's Point (68.4, 8.8)",
            rewards = {
                choice = {
                    {id = 17768, name = "Woodseed Hoop", slot = "Finger", quality = 2, icon = "inv_jewelry_ring_18"},
                    {id = 17778, name = "Sagebrush Girdle", slot = "Waist, Leather", quality = 2, icon = "inv_belt_25"},
                    {id = 17770, name = "Branchclaw Gauntlets", slot = "Hands, Plate", quality = 2, icon = "inv_gauntlets_30"},
                },
            },
            giver = "Talendria",
            giverLocation = "Desolace - Nijel's Point (68.4, 8.8)",
            objective = "Fill the Coated Cerulean Vial at the orange crystal pool in Maraudon.\nUse the Filled Cerulean Vial on the Vylestem Vines to force the corrupted Noxxious Scion to emerge.\nHeal 8 plants by killing these Noxxious Scion, then return to Talendria in Nijel's Point.",
        },
        {
            id = 7029,
            name = "Vyletongue Corruption",
            faction = "Horde",
            level = 47,
            minLevel = 41,
            prerequisites = "None. Starts with a Coated Cerulean Vial.",
            requiredItems = {
                {id = 17696, name = "Filled Cerulean Vial", where = "Fill the vial at an orange crystal pool outside the Orange side"},
            },
            where = "Use the vial on Vylestem Vines (Orange and Purple wings) and kill the 8 Noxxious Scions that emerge.",
            turnin = "Vark Battlescar",
            turninLocation = "Desolace - Shadowprey Village (23.2, 70.2)",
            rewards = {
                choice = {
                    {id = 17768, name = "Woodseed Hoop", slot = "Finger", quality = 2, icon = "inv_jewelry_ring_18"},
                    {id = 17778, name = "Sagebrush Girdle", slot = "Waist, Leather", quality = 2, icon = "inv_belt_25"},
                    {id = 17770, name = "Branchclaw Gauntlets", slot = "Hands, Plate", quality = 2, icon = "inv_gauntlets_30"},
                },
            },
            giver = "Vark Battlescar",
            giverLocation = "Desolace - Shadowprey Village (23.2, 70.2)",
            objective = "Fill the Coated Cerulean Vial at the orange crystal pool in Maraudon.\nUse the Filled Cerulean Vial on the Vylestem Vines to force the corrupted Noxxious Scion to emerge.\nHeal 8 plants by killing these Noxxious Scion, then return to Vark Battlescar in Shadowprey Village.",
        },
        {
            id = 7028,
            name = "Twisted Evils",
            faction = "Both",
            level = 47,
            minLevel = 41,
            prerequisites = "None.",
            requiredItems = {
                {id = 17684, name = "Theradric Crystal Carving", where = "Most Maraudon mobs (AzerothCore: 80%)"},
            },
            turnin = "Willow",
            turninLocation = "Desolace (62.2, 39.6)",
            rewards = {
                choice = {
                    {id = 17775, name = "Acumen Robes", slot = "Chest, Cloth", quality = 2, icon = "inv_chest_cloth_49"},
                    {id = 17776, name = "Sprightring Helm", slot = "Head, Leather", quality = 2, icon = "inv_helmet_35"},
                    {id = 17777, name = "Relentless Chain", slot = "Chest, Mail", quality = 2, icon = "inv_chest_chain_07"},
                    {id = 17779, name = "Hulkstone Pauldrons", slot = "Shoulder, Plate", quality = 2, icon = "inv_shoulder_23"},
                },
            },
            notes = "AtlasQuest says 25 carvings; AzerothCore requires 15.",
            giver = "Willow",
            giverLocation = "Desolace (62.2, 39.6)",
            objective = "Collect 25 Theradric Crystal Carvings for Willow in Desolace.",
        },
        {
            id = 7067,
            name = "The Pariah's Instructions",
            faction = "Both",
            level = 48,
            minLevel = 39,
            prerequisites = "None. Starts from The Pariah's Instructions (item).",
            requiredItems = {
                {
                    id = 17758,
                    name = "Amulet of Union",
                    where = "Combine the gems of the five Khans (Kolk, Gelk, Magra outside; Maraudos Purple [4]; Veng Orange [1])",
                },
            },
            turnin = "Centaur Pariah",
            turninLocation = "Desolace (roams around 50.4, 86.6)",
            rewards = {
                money = 14000,
                items = {
                    {id = 17774, name = "Mark of the Chosen", slot = "Trinket", quality = 2, icon = "inv_jewelry_talisman_08"},
                },
            },
            giver = "Centaur Pariah",
            giverLocation = "Desolace (Roams around 50.4, 86.6)",
            objective = "Read the Pariah's Instructions. Afterwards, obtain the Amulet of Union from Maraudon and return it to the Centaur Pariah in southern Desolace.",
        },
        {
            id = 7044,
            name = "Legends of Maraudon",
            faction = "Both",
            level = 49,
            minLevel = 41,
            prerequisites = "None.",
            requiredItems = {
                {id = 17702, name = "Celebrian Rod", where = "Noxxion (Orange [2])"},
                {id = 17703, name = "Celebrian Diamond", where = "Lord Vyletongue (Purple [5])"},
            },
            where = "Noxxion [2] here; Lord Vyletongue is in the Purple wing. Cavindra waits at the start of the Orange side, before the instance portal.",
            turnin = "Celebras the Redeemed",
            turninLocation = "Maraudon - Purple wing [7] (after defeating Celebras the Cursed)",
            followUp = "The Scepter of Celebras (7046)",
            rewards = {},
            giver = "Cavindra",
            giverLocation = "Desolace - Maraudon [4] on Entrance Map)",
            objective = "Recover the two parts of the Scepter of Celebras: the Celebrian Rod and the Celebrian Diamond.\nFind a way to speak with Celebras.",
        },
    },
    preparation = {
        {
            title = "Level",
            lines = {
                "Atlas gives one range for all of Maraudon (42-51, entry from 30); this wing's range is taken from its creature levels (Individual Progression / AzerothCore).",
            },
        },
        {
            title = "Access",
            lines = {
                "Maraudon is in western Desolace. Walk through the outdoor cave (entrance map): the Orange and Purple instance portals are at [C] and [B]; the Scepter portal is at [D].",
                "Wings in 3.3.5: Orange Crystals (Foulspore Cavern), Purple Crystals (Wicked Grotto) and Pristine Waters (Inner Maraudon / Earth Song Falls). AzerothCore lfg_dungeon_template / areatrigger_teleport.",
            },
        },
        {
            title = "Scepter of Celebras (portal shortcut)",
            lines = {
                "Legends of Maraudon (Cavindra, outside the Orange side): Celebrian Rod from Noxxion (Orange [2]) + Celebrian Diamond from Lord Vyletongue (Purple [5]).",
                "Defeat Celebras the Cursed (Purple [7]); Celebras the Redeemed then appears. Accept The Scepter of Celebras and wait for his ritual.",
                "Individual Progression: the Portal to Inner Maraudon at [D] on the entrance map is only visible to a player who carries the Scepter of Celebras. It takes the group straight to Inner Maraudon (Pristine Waters).",
            },
        },
        {
            title = "The Pariah's Instructions (Khans)",
            lines = {
                "Kill The Nameless Prophet (entrance [A]) for the Amulet of Spirits; use it to make each Khan's spirit manifest.",
                "Kolk, Gelk and Magra are in the outdoor entrance cave; Maraudos is in the Purple wing [4] and Veng in the Orange wing [1].",
            },
        },
        {
            title = "Server rules (restored Vanilla AI)",
            lines = {
                "Creeping Sludges leave a poison cloud when they die.",
                "Barbed Lashers knock the group down; Constrictor Vines root.",
                "Bring cure poison.",
            },
        },
    },
})
