-- Maraudon - Inner Maraudon (Vanilla batch 5, v0.3.5)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/Maraudon.blp + MaraudonEnt.blp + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (Maraudon2), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/dungeon_maraudon.sql / instance_maraudon.cpp smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    location = "Desolace",
    tag = "Dungeon",
    art = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenMaraudon",
    artFallback = SDJ.MAPS .. "Maraudon",
    crop = {0.04, 0.96, 0.29, 0.73},
    fallbackCrop = {0.0, 1.0, 0.25, 0.7},
    minLevel = "30",
    id = "mara_i",
    name = "Maraudon - Inner Maraudon",
    level = "46-51",
    maps = {
        {
            name = "Maraudon (Pristine Waters)",
            texture = SDJ.MAPS .. "Maraudon",
            coords = {0, 1, 0, 1},
            legend = {
                {"C", "Entrance (Portal)", "blue"},
                {"8", "Landslide"},
                {"9", "Tinkerer Gizlock"},
                {"10", "Rotgrip"},
                {"11", "Princess Theradras"},
                {"12", "Elder Splitrock (Lunar Festival)"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL. Shared map of all three wings; only this wing's markers are listed.",
        },
        {
            name = "Maraudon (Entrance)",
            texture = SDJ.MAPS .. "MaraudonEnt",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"", "The Nameless Prophet (Amulet of Spirits)"},
                {"B", "Maraudon (Purple)", "blue"},
                {"C", "Maraudon (Orange)", "blue"},
                {"D", "Maraudon (Portal) - Scepter of Celebras", "blue"},
                {"1", "Kolk <The First Khan>"},
                {"2", "Gelk <The Second Khan>"},
                {"3", "Magra <The Third Khan>"},
                {"4", "Cavindra"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
    },
    trash = {
        mobs = {
            {
                name = "Primordial Behemoth",
                npc = 12206,
                level = "48-49 Elite",
                priority = 1,
                abilities = {
                    {spell = 21071, name = "Boulder", desc = "Throws boulders at range."},
                    {spell = 5568, name = "Trample", tag = "AOE", desc = "Damages nearby players."},
                },
                note = "",
            },
            {
                name = "Theradrim Guardian",
                npc = 11784,
                level = "47-48 Elite",
                priority = 2,
                abilities = {
                    {spell = 16790, name = "Knockdown", tag = "STUN", desc = "Stuns the target and nearby players."},
                    {spell = 21057, name = "Summon Theradrim Shardling", tag = "SUMMON", desc = "Splits into 3 Theradrim Shardlings when it dies."},
                },
                note = "Be ready for the Shardlings.",
            },
            {
                name = "Thessala Hydra",
                npc = 12207,
                level = "46-47 Elite",
                priority = 2,
                abilities = {
                    {spell = 21788, name = "Deadly Poison", tag = "POISON", desc = "Melee hits can poison."},
                    {spell = 3391, name = "Thrash", desc = "Extra attacks."},
                    {spell = 21790, name = "Aqua Jet", tag = "AOE", desc = "Frost damage and knock-back around it."},
                },
                note = "",
            },
            {
                name = "Subterranean Diemetradon",
                npc = 13323,
                level = "46-48 Elite",
                priority = 2,
                abilities = {
                    {spell = 8281, name = "Sonic Burst", tag = "SILENCE", desc = "Silences nearby players for 10 sec."},
                },
                note = "Casters keep distance.",
            },
            {
                name = "Stolid Snapjaw",
                npc = 13599,
                level = "46-47",
                priority = 3,
                abilities = {
                    {spell = 14104, name = "Spikes", desc = "Damages melee attackers."},
                },
                note = "Not elite.",
            },
            {
                name = "Deep Borer",
                npc = 11789,
                level = "46-48",
                priority = 3,
                abilities = {},
                note = "Not elite; no scripted abilities.",
            },
        },
        loot = {
            {
                id = 17684,
                name = "Theradric Crystal Carving",
                slot = "Quest Item",
                quality = 1,
                icon = "inv_jewelry_talisman_07",
                rate = "80%",
                note = "Twisted Evils (7028). AzerothCore: 80% from most Maraudon mobs and bosses.",
            },
        },
        lootNote = "AtlasLoot has no Maraudon trash table; quest drop from the AzerothCore loot tables.",
    },
    bosses = {
        {
            name = "Landslide",
            npc = 12203,
            level = "50 Elite",
            portrait = P .. "Landslide",
            summary = "Earth elemental [8] in the waterfall cave.",
            abilities = {
                {spell = 10101, name = "Knock Away", desc = "Knocks a player back."},
                {spell = 5568, name = "Trample", tag = "AOE", desc = "Damages nearby players."},
                {spell = 21808, name = "Landslide", tag = "SUMMON", desc = "Below 50%: stuns the area and summons Theradrim Shardlings."},
            },
            mechanics = {"Tank against a wall.", "Kill or tank the Shardlings below 50%."},
            loot = {
                {id = 17736, name = "Rockgrip Gauntlets", slot = "Hands, Mail", quality = 3, icon = "inv_gauntlets_28", rate = "23.09%"},
                {id = 17734, name = "Helm of the Mountain", slot = "Head, Plate", quality = 3, icon = "inv_helmet_20", rate = "20.87%"},
                {id = 17737, name = "Cloud Stone", slot = "Held In Off-hand", quality = 3, icon = "inv_misc_orb_01", rate = "19.99%"},
                {id = 17943, name = "Fist of Stone", slot = "One-Hand, Mace", quality = 3, icon = "inv_hammer_17", rate = "16.58%"},
            },
        },
        {
            name = "Tinkerer Gizlock",
            npc = 13601,
            level = "50 Elite",
            portrait = P .. "TinkererGizlock",
            summary = "Goblin engineer [9].",
            abilities = {
                {spell = 16100, name = "Shoot", desc = "Ranged attack."},
                {spell = 9143, name = "Bomb", tag = "AOE", desc = "Fire damage in an area."},
                {spell = 29419, name = "Flash Bomb", desc = "Makes beasts flee (pets)."},
                {spell = 21833, name = "Goblin Dragon Gun", tag = "AOE", desc = "Fire cone for 8 sec."},
            },
            mechanics = {
                "Stay out of the Dragon Gun cone.",
                "Hunter / warlock pets get feared by Flash Bomb.",
            },
            loot = {
                {id = 17719, name = "Inventor's Focal Sword", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_14", rate = "27.44%"},
                {id = 17718, name = "Gizlock's Hypertech Buckler", slot = "Off Hand, Shield", quality = 3, icon = "inv_shield_10", rate = "30.61%"},
                {id = 17717, name = "Megashot Rifle", slot = "Gun", quality = 3, icon = "inv_weapon_rifle_05", rate = "27.23%"},
            },
        },
        {
            name = "Rotgrip",
            npc = 13596,
            level = "50 Elite",
            portrait = P .. "Rotgrip",
            summary = "Albino crocolisk [10] in the lake.",
            abilities = {
                {spell = 15976, name = "Puncture", tag = "DOT", desc = "Bleed on the tank."},
                {spell = 16495, name = "Fatal Bite", desc = "Drains health from the tank."},
            },
            mechanics = {"Tank and spank."},
            loot = {
                {id = 17732, name = "Rotgrip Mantle", slot = "Shoulder, Cloth", quality = 3, icon = "inv_shoulder_05", rate = "25.73%"},
                {id = 17728, name = "Albino Crocscale Boots", slot = "Feet, Leather", quality = 3, icon = "inv_boots_05", rate = "26.20%"},
                {id = 17730, name = "Gatorbite Axe", slot = "Two-Hand, Axe", quality = 3, icon = "inv_axe_04", rate = "19.21%"},
            },
        },
        {
            name = "Princess Theradras",
            npc = 12201,
            level = "51 Elite",
            portrait = P .. "PrincessTheradras",
            summary = "Daughter of Therazane [11], final boss. Zaetar's Spirit appears when she dies (Seed of Life).",
            abilities = {
                {spell = 8876, name = "Thrash", desc = "Extra attacks."},
                {spell = 21832, name = "Boulder", desc = "Throws a boulder at a player."},
                {spell = 21909, name = "Dust Field", tag = "AOE", desc = "Damages and knocks back nearby players."},
                {spell = 21869, name = "Repulsive Gaze", tag = "FEAR", desc = "Paralyses the tank for 8 sec."},
            },
            mechanics = {
                "Repulsive Gaze drops her threat on the tank: keep the off-tank ready.",
                "Healers stay out of Dust Field range.",
            },
            loot = {
                {id = 17780, name = "Blade of Eternal Darkness", slot = "One-Hand, Dagger", quality = 4, icon = "inv_sword_09", rate = "0.20%"},
                {id = 17715, name = "Eye of Theradras", slot = "Head, Cloth", quality = 3, icon = "inv_crown_01", rate = "13.47%"},
                {id = 17714, name = "Bracers of the Stone Princess", slot = "Wrist, Mail", quality = 3, icon = "inv_bracer_14", rate = "20.06%"},
                {id = 17711, name = "Elemental Rockridge Leggings", slot = "Legs, Plate", quality = 3, icon = "inv_pants_04", rate = "14.96%"},
                {id = 17707, name = "Gemshard Heart", slot = "Neck", quality = 3, icon = "inv_stone_01", rate = "15.30%"},
                {id = 17713, name = "Blackstone Ring", slot = "Finger", quality = 3, icon = "inv_jewelry_ring_17", rate = "18.92%"},
                {id = 17710, name = "Charstone Dirk", slot = "One-Hand, Dagger", quality = 3, icon = "inv_weapon_shortblade_14", rate = "14.24%"},
                {id = 17766, name = "Princess Theradras' Scepter", slot = "Two-Hand, Mace", quality = 3, icon = "inv_hammer_10", rate = "16.44%"},
            },
        },
    },
    quests = {
        {
            id = 7065,
            name = "Corruption of Earth and Seed",
            faction = "Alliance",
            level = 51,
            minLevel = 45,
            prerequisites = "None.",
            where = "Kill Princess Theradras [11].",
            turnin = "Keeper Marandis",
            turninLocation = "Desolace - Nijel's Point (63.8, 10.6)",
            followUp = "Seed of Life (7066)",
            rewards = {
                reputation = "Cenarion Circle",
                choice = {
                    {id = 17705, name = "Thrash Blade", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_36"},
                    {id = 17743, name = "Resurgence Rod", slot = "Two-Hand, Staff", quality = 3, icon = "inv_staff_goldfeathered_01"},
                    {id = 17753, name = "Verdant Keeper's Aim", slot = "Bow", quality = 3, icon = "inv_weapon_bow_03"},
                },
            },
            giver = "Keeper Marandis",
            giverLocation = "Desolace - Nijel's Point (63.8, 10.6)",
            objective = "Slay Princess Theradras and return to Keeper Marandis at Nijel's Point in Desolace.",
        },
        {
            id = 7064,
            name = "Corruption of Earth and Seed",
            faction = "Horde",
            level = 51,
            minLevel = 45,
            prerequisites = "None.",
            where = "Kill Princess Theradras [11].",
            turnin = "Selendra",
            turninLocation = "Desolace (26.8, 77.6)",
            followUp = "Seed of Life (7066)",
            rewards = {
                reputation = "Cenarion Circle",
                choice = {
                    {id = 17705, name = "Thrash Blade", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_36"},
                    {id = 17743, name = "Resurgence Rod", slot = "Two-Hand, Staff", quality = 3, icon = "inv_staff_goldfeathered_01"},
                    {id = 17753, name = "Verdant Keeper's Aim", slot = "Bow", quality = 3, icon = "inv_weapon_bow_03"},
                },
            },
            giver = "Selendra",
            giverLocation = "Desolace (26.8, 77.6)",
            objective = "Slay Princess Theradras and return to Selendra near Shadowprey Village in Desolace.",
        },
        {
            id = 7066,
            name = "Seed of Life",
            faction = "Both",
            level = 51,
            minLevel = 39,
            giver = "Zaetar's Spirit",
            giverLocation = "Maraudon [11], after Princess Theradras dies",
            prerequisites = "None in AzerothCore (AtlasQuest lists Corruption of Earth and Seed first).",
            requiredItems = {
                {id = 17760, name = "Seed of Life", where = "Given by Zaetar's Spirit"},
            },
            turnin = "Keeper Remulos",
            turninLocation = "Moonglade - Shrine of Remulos (36.2, 41.8)",
            rewards = {money = 15000, reputation = "Cenarion Circle"},
            objective = "Seek out Remulos in Moonglade and give him the Seed of Life.",
        },
        {
            id = 7028,
            name = "Twisted Evils",
            faction = "Both",
            level = 47,
            minLevel = 41,
            prerequisites = "None.",
            requiredItems = {
                {id = 17684, name = "Theradric Crystal Carving", where = "Most Maraudon mobs (AzerothCore: 80%)"},
            },
            turnin = "Willow",
            turninLocation = "Desolace (62.2, 39.6)",
            rewards = {
                choice = {
                    {id = 17775, name = "Acumen Robes", slot = "Chest, Cloth", quality = 2, icon = "inv_chest_cloth_49"},
                    {id = 17776, name = "Sprightring Helm", slot = "Head, Leather", quality = 2, icon = "inv_helmet_35"},
                    {id = 17777, name = "Relentless Chain", slot = "Chest, Mail", quality = 2, icon = "inv_chest_chain_07"},
                    {id = 17779, name = "Hulkstone Pauldrons", slot = "Shoulder, Plate", quality = 2, icon = "inv_shoulder_23"},
                },
            },
            notes = "AtlasQuest says 25 carvings; AzerothCore requires 15.",
            giver = "Willow",
            giverLocation = "Desolace (62.2, 39.6)",
            objective = "Collect 25 Theradric Crystal Carvings for Willow in Desolace.",
        },
    },
    preparation = {
        {
            title = "Level",
            lines = {
                "Atlas gives one range for all of Maraudon (42-51, entry from 30); this wing's range is taken from its creature levels (Individual Progression / AzerothCore).",
            },
        },
        {
            title = "Access",
            lines = {
                "Reach Inner Maraudon through the end of the Orange or Purple wing (down the waterfall), or directly with the Scepter of Celebras portal.",
                "AzerothCore lists this wing as \"Maraudon - Pristine Waters\".",
            },
        },
        {
            title = "Scepter of Celebras (portal shortcut)",
            lines = {
                "Legends of Maraudon (Cavindra, outside the Orange side): Celebrian Rod from Noxxion (Orange [2]) + Celebrian Diamond from Lord Vyletongue (Purple [5]).",
                "Defeat Celebras the Cursed (Purple [7]); Celebras the Redeemed then appears. Accept The Scepter of Celebras and wait for his ritual.",
                "Individual Progression: the Portal to Inner Maraudon at [D] on the entrance map is only visible to a player who carries the Scepter of Celebras. It takes the group straight to Inner Maraudon (Pristine Waters).",
            },
        },
        {
            title = "Server rules (restored Vanilla AI)",
            lines = {
                "Theradrim Guardians split into 3 Shardlings on death.",
                "Subterranean Diemetradons silence: casters keep distance.",
            },
        },
    },
})
