-- Maraudon - Purple Side (Vanilla batch 5, v0.3.5)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/Maraudon.blp + MaraudonEnt.blp + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (Maraudon1/2), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/dungeon_maraudon.sql / instance_maraudon.cpp smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    location = "Desolace",
    tag = "Dungeon",
    art = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenMaraudon",
    artFallback = SDJ.MAPS .. "Maraudon",
    crop = {0.04, 0.96, 0.29, 0.73},
    fallbackCrop = {0.0, 1.0, 0.25, 0.7},
    minLevel = "30",
    id = "mara_p",
    name = "Maraudon - Purple Side",
    level = "42-49",
    maps = {
        {
            name = "Maraudon (Purple: Wicked Grotto)",
            texture = SDJ.MAPS .. "Maraudon",
            coords = {0, 1, 0, 1},
            legend = {
                {"B", "Entrance (Purple)", "blue"},
                {"4", "Maraudos <The Fourth Khan>"},
                {"5", "Lord Vyletongue"},
                {"6", "Meshlok the Harvester (Rare)"},
                {"7", "Celebras the Cursed"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL. Shared map of all three wings; only this wing's markers are listed.",
        },
        {
            name = "Maraudon (Entrance)",
            texture = SDJ.MAPS .. "MaraudonEnt",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"", "The Nameless Prophet (Amulet of Spirits)"},
                {"B", "Maraudon (Purple)", "blue"},
                {"C", "Maraudon (Orange)", "blue"},
                {"D", "Maraudon (Portal) - Scepter of Celebras", "blue"},
                {"1", "Kolk <The First Khan>"},
                {"2", "Gelk <The Second Khan>"},
                {"3", "Magra <The Third Khan>"},
                {"4", "Cavindra"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
    },
    trash = {
        mobs = {
            {
                name = "Putridus Trickster",
                npc = 11791,
                level = "44-45 Elite",
                priority = 1,
                abilities = {
                    {spell = 21061, name = "Putrid Breath", desc = "Melee hits can cause Putrid Breath."},
                    {spell = 8876, name = "Thrash", desc = "Extra attacks."},
                    {spell = 13299, name = "Poison Proc", tag = "POISON", desc = "Melee hits can poison."},
                    {spell = 15657, name = "Backstab", desc = "From behind."},
                },
                note = "",
            },
            {
                name = "Putridus Satyr",
                npc = 11790,
                level = "43-44 Elite",
                priority = 2,
                abilities = {
                    {spell = 21061, name = "Putrid Breath", desc = "Melee hits can cause Putrid Breath."},
                    {spell = 14873, name = "Sinister Strike", desc = "Instant melee strike."},
                    {spell = 12540, name = "Gouge", tag = "CC", desc = "Incapacitates a player for 4 sec."},
                },
                note = "",
            },
            {
                name = "Putridus Shadowstalker",
                npc = 11792,
                level = "42-44 Elite",
                priority = 2,
                abilities = {
                    {spell = 22766, name = "Sneak", desc = "Stealthed."},
                    {spell = 9080, name = "Hamstring", tag = "SNARE", desc = "Slows a player."},
                    {spell = 15087, name = "Evasion", desc = "Dodges more for 15 sec."},
                },
                note = "Stealthed: watch for ambushes.",
            },
            {
                name = "Sister of Celebras",
                npc = 11794,
                level = "45 Elite",
                priority = 2,
                abilities = {
                    {spell = 15795, name = "Throw", desc = "Ranged attack."},
                    {spell = 14516, name = "Strike", desc = "Melee hit."},
                },
                note = "",
            },
            {
                name = "Poison Sprite",
                npc = 12216,
                level = "42-43",
                priority = 3,
                abilities = {
                    {spell = 21067, name = "Poison Bolt", tag = "POISON", desc = "Nature damage over time."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Not elite.",
            },
            {
                name = "Corruptor",
                npc = 12217,
                level = "42-43",
                priority = 2,
                abilities = {
                    {spell = 21068, name = "Corruption", tag = "DOT", desc = "Shadow damage over time."},
                    {spell = 5413, name = "Noxious Catalyst", tag = "DEBUFF", desc = "Lowers Nature resistance."},
                },
                note = "Not elite.",
            },
            {
                name = "Noxious Slime",
                npc = 12221,
                level = "46-47 Elite",
                priority = 2,
                abilities = {
                    {spell = 21070, name = "Noxious Cloud", tag = "AOE", desc = "Poison cloud in melee range and when it dies."},
                },
                note = "",
            },
            {
                name = "Creeping Sludge",
                npc = 12222,
                level = "45-46 Elite",
                priority = 2,
                abilities = {
                    {spell = 21070, name = "Noxious Cloud", tag = "AOE", desc = "Poison cloud in melee range and when it dies."},
                },
                note = "",
            },
            {
                name = "Constrictor Vine",
                npc = 12220,
                level = "45-46 Elite",
                priority = 2,
                abilities = {
                    {spell = 11922, name = "Entangling Roots", tag = "ROOT", desc = "Roots a player and deals Nature damage."},
                },
                note = "",
            },
            {
                name = "Barbed Lasher",
                npc = 12219,
                level = "44-45 Elite",
                priority = 2,
                abilities = {
                    {spell = 21749, name = "Thorn Volley", tag = "AOE", desc = "Damages and knocks down nearby players."},
                },
                note = "",
            },
            {
                name = "Deeprot Tangler",
                npc = 13142,
                level = "44-45 Elite",
                priority = 2,
                abilities = {
                    {spell = 21337, name = "Thorns", desc = "Buffed with Thorns."},
                    {spell = 21331, name = "Entangling Roots", tag = "ROOT", desc = "Roots a player."},
                },
                note = "",
            },
            {
                name = "Deeprot Stomper",
                npc = 13141,
                level = "43-44 Elite",
                priority = 2,
                abilities = {
                    {spell = 13446, name = "Strike", desc = "Heavy melee hit."},
                    {spell = 11876, name = "War Stomp", tag = "STUN", desc = "Stuns and knocks back nearby players."},
                },
                note = "",
            },
            {
                name = "Cavern Lurker",
                npc = 12223,
                level = "45-46 Elite",
                priority = 3,
                abilities = {
                    {spell = 11428, name = "Knockdown", tag = "STUN", desc = "Stuns a player for 2 sec."},
                },
                note = "",
            },
            {
                name = "Cavern Shambler",
                npc = 12224,
                level = "46-47 Elite",
                priority = 2,
                abilities = {
                    {spell = 7948, name = "Wild Regeneration", tag = "HEAL", desc = "Heals itself below 75% health."},
                    {spell = 16790, name = "Knockdown", tag = "STUN", desc = "Stuns the target and nearby players."},
                },
                note = "Interrupt Wild Regeneration.",
            },
            {
                name = "Noxxious Scion",
                npc = 13696,
                level = "45-46",
                priority = 3,
                abilities = {
                    {spell = 21068, name = "Corruption", tag = "DOT", desc = "Shadow damage over time."},
                    {spell = 5413, name = "Noxious Catalyst", tag = "DEBUFF", desc = "Lowers Nature resistance."},
                },
                note = "Emerges from Vylestem Vines when you use the Filled Cerulean Vial (Vyletongue Corruption).",
            },
        },
        loot = {
            {
                id = 17684,
                name = "Theradric Crystal Carving",
                slot = "Quest Item",
                quality = 1,
                icon = "inv_jewelry_talisman_07",
                rate = "80%",
                note = "Twisted Evils (7028). AzerothCore: 80% from most Maraudon mobs and bosses.",
            },
        },
        lootNote = "AtlasLoot has no Maraudon trash table; quest drop from the AzerothCore loot tables.",
    },
    bosses = {
        {
            name = "Maraudos",
            npc = 13739,
            level = "46 Elite",
            optional = true,
            portrait = P .. "Maraudos",
            summary = "The Fourth Khan [4]. Appears as the Spirit of Maraudos; the Amulet of Spirits makes him manifest (The Pariah's Instructions).",
            abilities = {
                {spell = 15795, name = "Throw", desc = "Ranged attack."},
                {spell = 14873, name = "Sinister Strike", desc = "Instant melee strike."},
            },
            mechanics = {
                "Use the Amulet of Spirits on the Spirit of Maraudos.",
                "Abilities are from the AzerothCore script of the Spirit of Maraudos.",
            },
            loot = {
                {
                    id = 17764,
                    name = "Gem of the Fourth Khan",
                    slot = "Quest Item",
                    quality = 1,
                    icon = "inv_misc_gem_sapphire_02",
                    rate = "100%",
                    note = "The Pariah's Instructions (7067).",
                },
            },
        },
        {
            name = "Lord Vyletongue",
            npc = 12236,
            level = "47 Elite",
            portrait = P .. "LordVyletongue",
            summary = "Satyr lord [5]. Drops the Celebrian Diamond.",
            abilities = {
                {spell = 16100, name = "Shoot", desc = "Ranged attack."},
                {spell = 21390, name = "Multi-Shot", tag = "AOE", desc = "Hits the target and nearby players."},
                {spell = 21655, name = "Blink", desc = "Teleports 20 yd."},
                {spell = 7964, name = "Smoke Bomb", tag = "STUN", desc = "Stuns nearby players for 4 sec."},
            },
            mechanics = {
                "Clear the satyrs around him first.",
                "He blinks away every 15 sec; ranged keep damage on him.",
            },
            loot = {
                {id = 17755, name = "Satyrmane Sash", slot = "Waist, Cloth", quality = 3, icon = "inv_belt_24", rate = "25.71%"},
                {id = 17754, name = "Infernal Trickster Leggings", slot = "Legs, Mail", quality = 3, icon = "inv_pants_wolf", rate = "28.09%"},
                {id = 17752, name = "Satyr's Lash", slot = "One-Hand, Dagger", quality = 3, icon = "inv_weapon_shortblade_09", rate = "23.14%"},
                {
                    id = 17703,
                    name = "Celebrian Diamond",
                    slot = "Quest Item",
                    quality = 1,
                    icon = "inv_jewelry_talisman_08",
                    rate = "100%",
                    note = "Legends of Maraudon (7044).",
                },
            },
        },
        {
            name = "Meshlok the Harvester",
            npc = 12237,
            level = "48 Rare Elite",
            optional = true,
            rare = true,
            portrait = P .. "MeshlokTheHarvester",
            summary = "Rare [6]. AzerothCore despawns him 85% of the time (about 15% of runs).",
            abilities = {
                {spell = 13446, name = "Strike", desc = "Heavy melee hit."},
                {spell = 15593, name = "War Stomp", tag = "STUN", desc = "Stuns nearby players for 8 sec."},
            },
            mechanics = {"Spread healers out of War Stomp range."},
            loot = {
                {id = 17741, name = "Nature's Embrace", slot = "Chest, Cloth", quality = 3, icon = "inv_chest_cloth_15", rate = "30.34%"},
                {id = 17742, name = "Fungus Shroud Armor", slot = "Chest, Leather", quality = 3, icon = "inv_chest_leather_08", rate = "31.37%"},
                {id = 17767, name = "Bloomsprout Headpiece", slot = "Head, Mail", quality = 3, icon = "inv_helmet_17", rate = "28.32%"},
            },
        },
        {
            name = "Celebras the Cursed",
            npc = 12225,
            level = "49 Elite",
            portrait = P .. "CelebrasTheCursed",
            summary = "Cursed son of Zaetar [7], end of the Purple wing. Celebras the Redeemed appears when he dies.",
            abilities = {
                {spell = 21807, name = "Wrath", desc = "Nature nuke."},
                {spell = 21793, name = "Twisted Tranquility", tag = "AOE", desc = "Channelled Nature damage around him."},
                {spell = 21968, name = "Corrupt Forces of Nature", tag = "SUMMON", desc = "Summons 3 Corrupt Forces of Nature."},
                {spell = 12747, name = "Entangling Roots", tag = "ROOT", desc = "Roots a player."},
            },
            mechanics = {
                "Interrupt Twisted Tranquility.",
                "Pick up the Corrupt Forces of Nature.",
                "Talk to Celebras the Redeemed afterwards for Legends of Maraudon / The Scepter of Celebras.",
            },
            loot = {
                {id = 17739, name = "Grovekeeper's Drape", slot = "Back", quality = 3, icon = "inv_misc_cape_17", rate = "30.32%"},
                {id = 17740, name = "Soothsayer's Headdress", slot = "Head, Leather", quality = 3, icon = "inv_helmet_12", rate = "28.59%"},
                {id = 17738, name = "Claw of Celebras", slot = "Off Hand, Fist Weapon", quality = 3, icon = "ability_whirlwind", rate = "28.22%"},
            },
        },
    },
    quests = {
        {
            id = 7070,
            name = "Shadowshard Fragments",
            faction = "Alliance",
            level = 42,
            minLevel = 39,
            prerequisites = "None.",
            requiredItems = {
                {id = 17756, name = "Shadowshard Fragment", where = "Shadowshard Rumblers / Smashers outside the Purple side (AzerothCore: 80%)"},
            },
            turnin = "Archmage Tervosh",
            turninLocation = "Dustwallow Marsh - Theramore Isle (66.4, 49.2)",
            rewards = {
                reputation = "Stormwind",
                choice = {
                    {id = 17772, name = "Zealous Shadowshard Pendant", slot = "Neck", quality = 2, icon = "inv_jewelry_necklace_06"},
                    {id = 17773, name = "Prodigious Shadowshard Pendant", slot = "Neck", quality = 2, icon = "inv_jewelry_necklace_06"},
                },
            },
            giver = "Archmage Tervosh",
            giverLocation = "Dustwallow Marsh - Theramore Isle (66.4, 49.2)",
            objective = "Collect 10 Shadowshard Fragments from Maraudon and return them to Archmage Tervosh in Theramore on the coast of Dustwallow Marsh.",
        },
        {
            id = 7068,
            name = "Shadowshard Fragments",
            faction = "Horde",
            level = 42,
            minLevel = 39,
            prerequisites = "None.",
            requiredItems = {
                {id = 17756, name = "Shadowshard Fragment", where = "Shadowshard Rumblers / Smashers outside the Purple side (AzerothCore: 80%)"},
            },
            turnin = "Uthel'nay",
            turninLocation = "Orgrimmar - Valley of Spirits (39.0, 86.0)",
            rewards = {
                reputation = "Darkspear Trolls",
                choice = {
                    {id = 17772, name = "Zealous Shadowshard Pendant", slot = "Neck", quality = 2, icon = "inv_jewelry_necklace_06"},
                    {id = 17773, name = "Prodigious Shadowshard Pendant", slot = "Neck", quality = 2, icon = "inv_jewelry_necklace_06"},
                },
            },
            giver = "Uthel'nay",
            giverLocation = "Orgrimmar - Valley of Spirits (39.0, 86.0)",
            objective = "Collect 10 Shadowshard Fragments from Maraudon and return them to Uthel'nay in Orgrimmar",
        },
        {
            id = 7041,
            name = "Vyletongue Corruption",
            faction = "Alliance",
            level = 47,
            minLevel = 41,
            prerequisites = "None. Starts with a Coated Cerulean Vial.",
            requiredItems = {
                {id = 17696, name = "Filled Cerulean Vial", where = "Fill the vial at an orange crystal pool outside the Orange side"},
            },
            where = "Use the vial on Vylestem Vines (Orange and Purple wings) and kill the 8 Noxxious Scions that emerge.",
            turnin = "Talendria",
            turninLocation = "Desolace - Nijel's Point (68.4, 8.8)",
            rewards = {
                choice = {
                    {id = 17768, name = "Woodseed Hoop", slot = "Finger", quality = 2, icon = "inv_jewelry_ring_18"},
                    {id = 17778, name = "Sagebrush Girdle", slot = "Waist, Leather", quality = 2, icon = "inv_belt_25"},
                    {id = 17770, name = "Branchclaw Gauntlets", slot = "Hands, Plate", quality = 2, icon = "inv_gauntlets_30"},
                },
            },
            giver = "Talendria",
            giverLocation = "Desolace - Nijel's Point (68.4, 8.8)",
            objective = "Fill the Coated Cerulean Vial at the orange crystal pool in Maraudon.\nUse the Filled Cerulean Vial on the Vylestem Vines to force the corrupted Noxxious Scion to emerge.\nHeal 8 plants by killing these Noxxious Scion, then return to Talendria in Nijel's Point.",
        },
        {
            id = 7029,
            name = "Vyletongue Corruption",
            faction = "Horde",
            level = 47,
            minLevel = 41,
            prerequisites = "None. Starts with a Coated Cerulean Vial.",
            requiredItems = {
                {id = 17696, name = "Filled Cerulean Vial", where = "Fill the vial at an orange crystal pool outside the Orange side"},
            },
            where = "Use the vial on Vylestem Vines (Orange and Purple wings) and kill the 8 Noxxious Scions that emerge.",
            turnin = "Vark Battlescar",
            turninLocation = "Desolace - Shadowprey Village (23.2, 70.2)",
            rewards = {
                choice = {
                    {id = 17768, name = "Woodseed Hoop", slot = "Finger", quality = 2, icon = "inv_jewelry_ring_18"},
                    {id = 17778, name = "Sagebrush Girdle", slot = "Waist, Leather", quality = 2, icon = "inv_belt_25"},
                    {id = 17770, name = "Branchclaw Gauntlets", slot = "Hands, Plate", quality = 2, icon = "inv_gauntlets_30"},
                },
            },
            giver = "Vark Battlescar",
            giverLocation = "Desolace - Shadowprey Village (23.2, 70.2)",
            objective = "Fill the Coated Cerulean Vial at the orange crystal pool in Maraudon.\nUse the Filled Cerulean Vial on the Vylestem Vines to force the corrupted Noxxious Scion to emerge.\nHeal 8 plants by killing these Noxxious Scion, then return to Vark Battlescar in Shadowprey Village.",
        },
        {
            id = 7028,
            name = "Twisted Evils",
            faction = "Both",
            level = 47,
            minLevel = 41,
            prerequisites = "None.",
            requiredItems = {
                {id = 17684, name = "Theradric Crystal Carving", where = "Most Maraudon mobs (AzerothCore: 80%)"},
            },
            turnin = "Willow",
            turninLocation = "Desolace (62.2, 39.6)",
            rewards = {
                choice = {
                    {id = 17775, name = "Acumen Robes", slot = "Chest, Cloth", quality = 2, icon = "inv_chest_cloth_49"},
                    {id = 17776, name = "Sprightring Helm", slot = "Head, Leather", quality = 2, icon = "inv_helmet_35"},
                    {id = 17777, name = "Relentless Chain", slot = "Chest, Mail", quality = 2, icon = "inv_chest_chain_07"},
                    {id = 17779, name = "Hulkstone Pauldrons", slot = "Shoulder, Plate", quality = 2, icon = "inv_shoulder_23"},
                },
            },
            notes = "AtlasQuest says 25 carvings; AzerothCore requires 15.",
            giver = "Willow",
            giverLocation = "Desolace (62.2, 39.6)",
            objective = "Collect 25 Theradric Crystal Carvings for Willow in Desolace.",
        },
        {
            id = 7067,
            name = "The Pariah's Instructions",
            faction = "Both",
            level = 48,
            minLevel = 39,
            prerequisites = "None. Starts from The Pariah's Instructions (item).",
            requiredItems = {
                {
                    id = 17758,
                    name = "Amulet of Union",
                    where = "Combine the gems of the five Khans (Kolk, Gelk, Magra outside; Maraudos Purple [4]; Veng Orange [1])",
                },
            },
            turnin = "Centaur Pariah",
            turninLocation = "Desolace (roams around 50.4, 86.6)",
            rewards = {
                money = 14000,
                items = {
                    {id = 17774, name = "Mark of the Chosen", slot = "Trinket", quality = 2, icon = "inv_jewelry_talisman_08"},
                },
            },
            giver = "Centaur Pariah",
            giverLocation = "Desolace (Roams around 50.4, 86.6)",
            objective = "Read the Pariah's Instructions. Afterwards, obtain the Amulet of Union from Maraudon and return it to the Centaur Pariah in southern Desolace.",
        },
        {
            id = 7044,
            name = "Legends of Maraudon",
            faction = "Both",
            level = 49,
            minLevel = 41,
            prerequisites = "None.",
            requiredItems = {
                {id = 17702, name = "Celebrian Rod", where = "Noxxion (Orange [2])"},
                {id = 17703, name = "Celebrian Diamond", where = "Lord Vyletongue (Purple [5])"},
            },
            where = "Lord Vyletongue [5] here; Noxxion is in the Orange wing. Defeat Celebras the Cursed [7] to speak with Celebras the Redeemed.",
            turnin = "Celebras the Redeemed",
            turninLocation = "Maraudon - Purple wing [7] (after defeating Celebras the Cursed)",
            followUp = "The Scepter of Celebras (7046)",
            rewards = {},
            giver = "Cavindra",
            giverLocation = "Desolace - Maraudon [4] on Entrance Map)",
            objective = "Recover the two parts of the Scepter of Celebras: the Celebrian Rod and the Celebrian Diamond.\nFind a way to speak with Celebras.",
        },
        {
            id = 7046,
            name = "The Scepter of Celebras",
            faction = "Both",
            level = 49,
            minLevel = 41,
            prerequisites = "Legends of Maraudon (7044).",
            where = "Stay with Celebras the Redeemed [7] while he performs the ritual.",
            turnin = "Celebras the Redeemed",
            turninLocation = "Maraudon - Purple wing [7]",
            chain = {
                {id = 7044, name = "Legends of Maraudon", text = "Rod (Noxxion) + Diamond (Vyletongue)."},
                {id = 7046, name = "The Scepter of Celebras", text = "(this quest)"},
            },
            rewards = {
                items = {
                    {id = 17191, name = "Scepter of Celebras", slot = "Two-Hand, Staff", quality = 3, icon = "inv_staff_16"},
                },
            },
            notes = "The Scepter opens the portal shortcut to Inner Maraudon (see Preparation).",
            giver = "Celebras the Redeemed",
            giverLocation = "Maraudon [7]",
            objective = "Assist Celebras the Redeemed while he creates the Scepter of Celebras.\nSpeak with him when the ritual is complete.",
        },
    },
    preparation = {
        {
            title = "Level",
            lines = {
                "Atlas gives one range for all of Maraudon (42-51, entry from 30); this wing's range is taken from its creature levels (Individual Progression / AzerothCore).",
            },
        },
        {
            title = "Access",
            lines = {
                "Maraudon is in western Desolace. Walk through the outdoor cave (entrance map): the Orange and Purple instance portals are at [C] and [B]; the Scepter portal is at [D].",
                "Wings in 3.3.5: Orange Crystals (Foulspore Cavern), Purple Crystals (Wicked Grotto) and Pristine Waters (Inner Maraudon / Earth Song Falls). AzerothCore lfg_dungeon_template / areatrigger_teleport.",
            },
        },
        {
            title = "Scepter of Celebras (portal shortcut)",
            lines = {
                "Legends of Maraudon (Cavindra, outside the Orange side): Celebrian Rod from Noxxion (Orange [2]) + Celebrian Diamond from Lord Vyletongue (Purple [5]).",
                "Defeat Celebras the Cursed (Purple [7]); Celebras the Redeemed then appears. Accept The Scepter of Celebras and wait for his ritual.",
                "Individual Progression: the Portal to Inner Maraudon at [D] on the entrance map is only visible to a player who carries the Scepter of Celebras. It takes the group straight to Inner Maraudon (Pristine Waters).",
            },
        },
        {
            title = "The Pariah's Instructions (Khans)",
            lines = {
                "Kill The Nameless Prophet (entrance [A]) for the Amulet of Spirits; use it to make each Khan's spirit manifest.",
                "Kolk, Gelk and Magra are in the outdoor entrance cave; Maraudos is in the Purple wing [4] and Veng in the Orange wing [1].",
            },
        },
        {
            title = "Server rules (restored Vanilla AI)",
            lines = {
                "Putridus Shadowstalkers are stealthed.",
                "Cavern Shamblers heal themselves: interrupt.",
                "Bring cure poison.",
            },
        },
    },
})
