-- Razorfen Downs (Vanilla batch 4, v0.3.4)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/RazorfenDowns.blp + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (RazorfenDowns1/2), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/vanilla_creatures.sql / dungeon SAI smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    id = "rfd",
    name = "Razorfen Downs",
    level = "33-42",
    minLevel = "25",
    location = "The Barrens",
    tag = "Dungeon",
    art = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenRazorfenDowns",
    artFallback = SDJ.MAPS .. "RazorfenDowns",
    crop = {0.04, 0.96, 0.29, 0.73},
    fallbackCrop = {0.0, 1.0, 0.25, 0.7},
    maps = {
        {
            name = "Razorfen Downs",
            texture = SDJ.MAPS .. "RazorfenDowns",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"1", "Tuten'kash"},
                {"2", "Henry Stern"},
                {"", "Belnistrasz"},
                {"", "Sah'rhee"},
                {"3", "Mordresh Fire Eye"},
                {"4", "Glutton"},
                {"5", "Ragglesnout (Rare, Varies)"},
                {"6", "Amnennar the Coldbringer"},
                {"7", "Plaguemaw the Rotting"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
    },
    trash = {
        mobs = {
            {
                name = "Death's Head Necromancer",
                npc = 7337,
                level = "36-37 Elite",
                priority = 1,
                abilities = {
                    {spell = 12420, name = "Summon Skeletal Servant", tag = "SUMMON", desc = "Has a Skeletal Servant out."},
                    {spell = 11445, name = "Bone Armor", desc = "On aggro: absorbs damage for 1 min."},
                    {spell = 11443, name = "Cripple", tag = "DEBUFF", desc = "Slows attacks and movement."},
                    {spell = 9613, name = "Shadow Bolt", desc = "3 sec Shadow nuke."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Kill first; interrupt Shadow Bolt.",
            },
            {
                name = "Death's Head Geomancer",
                npc = 7335,
                level = "35-36 Elite",
                priority = 1,
                abilities = {
                    {spell = 9053, name = "Fireball", desc = "3 sec Fire nuke."},
                    {spell = 8814, name = "Flame Spike", tag = "AOE", desc = "Fire damage in an area."},
                    {spell = 11436, name = "Slow", tag = "DEBUFF", desc = "Slows attacks, casting and movement."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Skeletal Summoner",
                npc = 7342,
                level = "39-40 Elite",
                priority = 1,
                abilities = {
                    {spell = 12258, name = "Summon Shadowcaster", tag = "SUMMON", desc = "Summons a Skeletal Shadowcaster."},
                    {spell = 9532, name = "Lightning Bolt", desc = "3 sec Nature nuke."},
                    {spell = 11980, name = "Curse of Weakness", tag = "CURSE", desc = "Less physical damage for 2 min."},
                },
                note = "Kill before it adds more casters.",
            },
            {
                name = "Frozen Soul",
                npc = 7352,
                level = "37-38 Elite",
                priority = 1,
                abilities = {
                    {spell = 12528, name = "Silence", tag = "SILENCE", desc = "Silences nearby players for 10 sec."},
                    {spell = 12531, name = "Chilling Touch", desc = "Slows attacks and movement."},
                },
                note = "Casters stay out of melee.",
            },
            {
                name = "Freezing Spirit",
                npc = 7353,
                level = "39-40 Elite",
                priority = 2,
                abilities = {
                    {spell = 15532, name = "Frost Nova", tag = "ROOT", desc = "Roots players within 10 yd."},
                    {spell = 12529, name = "Chilling Touch", desc = "Melee hits can slow you."},
                },
                note = "",
            },
            {
                name = "Skeletal Frostweaver",
                npc = 7341,
                level = "37-38 Elite",
                priority = 2,
                abilities = {
                    {spell = 9672, name = "Frostbolt", desc = "Frost nuke that slows."},
                },
                note = "",
            },
            {
                name = "Skeletal Shadowcaster",
                npc = 7340,
                level = "36",
                priority = 2,
                abilities = {
                    {spell = 9613, name = "Shadow Bolt", desc = "3 sec Shadow nuke."},
                    {spell = 12248, name = "Amplify Damage", tag = "DEBUFF", desc = "Target takes 50% more damage for 10 sec."},
                },
                note = "Summoned by Skeletal Summoners.",
            },
            {
                name = "Withered Spearhide",
                npc = 7332,
                level = "34-35 Elite",
                priority = 2,
                abilities = {
                    {spell = 6660, name = "Shoot", desc = "Ranged attack."},
                    {spell = 11397, name = "Diseased Shot", tag = "DISEASE", desc = "Ranged shot that lowers Strength."},
                    {spell = 8599, name = "Enrage", tag = "ENRAGE", desc = "Enrages at 30% health."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Withered Reaver",
                npc = 7328,
                level = "35-36 Elite",
                priority = 2,
                abilities = {
                    {spell = 40504, name = "Cleave", desc = "Hits up to 3 targets in front."},
                    {spell = 8599, name = "Enrage", tag = "ENRAGE", desc = "Enrages at 30% health."},
                },
                note = "",
            },
            {
                name = "Splinterbone Captain",
                npc = 7345,
                level = "39-40 Elite",
                priority = 2,
                abilities = {
                    {spell = 9128, name = "Battle Shout", desc = "On aggro: raises allies' attack power."},
                    {spell = 12461, name = "Backhand", tag = "STUN", desc = "Stuns for 2 sec."},
                },
                note = "",
            },
            {
                name = "Withered Warrior / Quilguard",
                npc = 7327,
                level = "34-35 Elite",
                priority = 3,
                abilities = {
                    {spell = 6268, name = "Rushing Charge", desc = "Charges on aggro (Warrior)."},
                    {spell = 8599, name = "Enrage", tag = "ENRAGE", desc = "Enrages at 30% health."},
                },
                note = "Quilguards only Enrage.",
            },
            {
                name = "Thorn Eater / Boneflayer Ghoul",
                npc = 7348,
                level = "37-38 Elite",
                priority = 3,
                abilities = {
                    {spell = 12539, name = "Ghoul Rot", tag = "DISEASE", desc = "Melee hits can infect you."},
                    {spell = 12538, name = "Ravenous Claw", desc = "Drains health (Thorn Eater)."},
                },
                note = "",
            },
            {
                name = "Splinterbone Centurion",
                npc = 7346,
                level = "38-39",
                priority = 3,
                abilities = {
                    {spell = 8078, name = "Thunderclap", tag = "AOE", desc = "Nature damage and slows nearby players."},
                },
                note = "Not elite.",
            },
            {
                name = "Splinterbone Warrior",
                npc = 7344,
                level = "37-38",
                priority = 3,
                abilities = {
                    {spell = 11971, name = "Sunder Armor", tag = "DEBUFF", desc = "Lowers armour; stacks."},
                },
                note = "Not elite.",
            },
            {
                name = "Tomb Fiend / Tomb Reaver",
                npc = 7351,
                level = "37 Elite",
                priority = 2,
                abilities = {
                    {spell = 745, name = "Web", tag = "ROOT", desc = "Roots a target for 5 sec (Reaver)."},
                },
                note = "Gong waves before Tuten'kash: 10 Tomb Fiends, then 4 Tomb Reavers.",
            },
        },
        loot = {
            {id = 10574, name = "Corpseshroud", slot = "Head, Cloth", quality = 3, icon = "inv_misc_cape_04", rate = "0.01%"},
            {id = 10581, name = "Death's Head Vestment", slot = "Chest, Cloth", quality = 3, icon = "inv_chest_leather_08", rate = "0.02%"},
            {id = 10578, name = "Thoughtcast Boots", slot = "Feet, Cloth", quality = 3, icon = "inv_boots_01", rate = "0.01%"},
            {id = 10583, name = "Quillward Harness", slot = "Chest, Leather", quality = 3, icon = "inv_chest_leather_08", rate = "0.01%"},
            {id = 10582, name = "Briar Tredders", slot = "Feet, Leather", quality = 3, icon = "inv_boots_08", rate = "0.02%"},
            {id = 10584, name = "Stormgale Fists", slot = "Hands, Mail", quality = 3, icon = "inv_gauntlets_11", rate = "0.02%"},
            {id = 10573, name = "Boneslasher", slot = "Two-Hand, Sword", quality = 3, icon = "inv_sword_41", rate = "0.01%"},
            {id = 10570, name = "Manslayer", slot = "Two-Hand, Axe", quality = 3, icon = "inv_axe_04", rate = "0.01%"},
            {id = 10571, name = "Ebony Boneclub", slot = "One-Hand, Mace", quality = 3, icon = "inv_misc_bone_10", rate = "0.01%"},
            {id = 10567, name = "Quillshooter", slot = "Bow", quality = 3, icon = "inv_weapon_bow_01", rate = "0.02%"},
            {id = 10572, name = "Freezing Shard", slot = "Ranged, Wand", quality = 3, icon = "inv_wand_01", rate = "0.01%"},
            {
                id = 4614,
                name = "Pendant of Myzrael",
                slot = "Starts a Quest",
                quality = 2,
                icon = "inv_jewelry_necklace_07",
                note = "Starts an Arathi Highlands quest (Pendant of Myzrael, 635). AzerothCore: 0.02-0.06% from quilboar and Scourge.",
            },
        },
        lootNote = "AtlasLoot RazorfenDowns2 \"Trash Mobs\", plus a quest-starting drop from the AzerothCore loot tables.",
    },
    bosses = {
        {
            name = "Tuten'kash",
            npc = 7355,
            level = "40 Elite",
            portrait = P .. "TutenKash",
            summary = "Giant spider [1], called by the gong.",
            abilities = {
                {spell = 12252, name = "Web Spray", tag = "ROOT", desc = "Roots players in a cone in front for 10 sec."},
                {spell = 12255, name = "Curse of Tuten'kash", tag = "CURSE", desc = "Nearby players cast 15% slower and attack 18% slower."},
            },
            mechanics = {
                "Use the gong: it brings 10 Tomb Fiends, then 4 Tomb Reavers, then Tuten'kash.",
                "Keep casters out of the front cone.",
                "Remove the curse.",
            },
            loot = {
                {id = 10776, name = "Silky Spider Cape", slot = "Back", quality = 3, icon = "inv_misc_cape_17", rate = "28.64%"},
                {id = 10777, name = "Arachnid Gloves", slot = "Hands, Leather", quality = 3, icon = "inv_gauntlets_32", rate = "28.95%"},
                {id = 10775, name = "Carapace of Tuten'kash", slot = "Chest, Plate", quality = 3, icon = "inv_chest_plate08", rate = "24.87%"},
            },
        },
        {
            name = "Mordresh Fire Eye",
            npc = 7357,
            level = "39 Elite",
            portrait = P .. "MordreshFireEye",
            summary = "Quilboar caster [3].",
            abilities = {
                {name = "Call for Help", tag = "SUMMON", desc = "On aggro, allies within 50 yd join."},
                {spell = 12466, name = "Fireball", desc = "3 sec Fire nuke."},
                {spell = 12470, name = "Fire Nova", tag = "AOE", desc = "Fire damage to players within 9 yd."},
            },
            mechanics = {"Clear the area first.", "Only the tank in melee; interrupt Fireball."},
            loot = {
                {id = 10771, name = "Deathmage Sash", slot = "Waist, Cloth", quality = 3, icon = "inv_belt_24", rate = "27.92%"},
                {id = 10769, name = "Glowing Eye of Mordresh", slot = "Neck", quality = 3, icon = "inv_misc_orb_03", rate = "29.11%"},
                {id = 10770, name = "Mordresh's Lifeless Skull", slot = "Held In Off-hand", quality = 3, icon = "inv_misc_bone_elfskull_01", rate = "29.59%"},
            },
        },
        {
            name = "Glutton",
            npc = 8567,
            level = "40 Elite",
            portrait = P .. "Glutton",
            summary = "Bloated quilboar [4].",
            abilities = {
                {spell = 12627, name = "Disease Cloud", tag = "AOE", desc = "Nature damage to players within 7 yd every 3 sec."},
                {spell = 12795, name = "Frenzy", tag = "ENRAGE", desc = "Frenzies at 50% and 15% health."},
            },
            mechanics = {"Ranged stay out of the Disease Cloud.", "Tank cooldowns for Frenzy."},
            loot = {
                {id = 10774, name = "Fleshhide Shoulders", slot = "Shoulder, Leather", quality = 3, icon = "inv_shoulder_28", rate = "42.15%"},
                {id = 10772, name = "Glutton's Cleaver", slot = "One-Hand, Axe", quality = 3, icon = "inv_axe_23", rate = "44.22%"},
            },
        },
        {
            name = "Ragglesnout",
            npc = 7354,
            level = "40 Elite",
            optional = true,
            rare = true,
            portrait = P .. "Ragglesnout",
            summary = "Rare quilboar [5]. Individual Progression despawns it 70% of the time (about 30% of runs).",
            abilities = {
                {spell = 12471, name = "Shadow Bolt", desc = "Shadow nuke."},
                {spell = 11639, name = "Shadow Word: Pain", tag = "DOT", desc = "Shadow damage over time."},
                {spell = 7645, name = "Dominate Mind", tag = "CC", desc = "Mind-controls a player for 10 sec."},
                {spell = 12039, name = "Heal", tag = "HEAL", desc = "Heals an ally below 40%."},
            },
            mechanics = {"Interrupt Heal.", "Crowd-control or avoid a dominated player."},
            loot = {
                {id = 10768, name = "Boar Champion's Belt", slot = "Waist, Mail", quality = 3, icon = "inv_belt_11", rate = "31.40%"},
                {id = 10758, name = "X'caliboar", slot = "Two-Hand, Sword", quality = 3, icon = "inv_sword_45", rate = "18.51%"},
                {id = 10767, name = "Savage Boar's Guard", slot = "Off Hand, Shield", quality = 3, icon = "inv_shield_17", rate = "35.14%"},
            },
        },
        {
            name = "Amnennar the Coldbringer",
            npc = 7358,
            level = "41 Elite",
            portrait = P .. "AmnennarTheColdbringer",
            summary = "Lich and final boss [6]. Kill target for Bring the Light and Bring the End.",
            abilities = {
                {spell = 15530, name = "Frostbolt", desc = "Frost nuke that slows."},
                {spell = 15531, name = "Frost Nova", tag = "ROOT", desc = "Roots players within 10 yd."},
                {spell = 13009, name = "Amnennar's Wrath", desc = "Knocks the target back."},
                {spell = 12642, name = "Summon Frost Spectres", tag = "SUMMON", desc = "Summons Frost Spectres at 55% and 30% health."},
                {spell = 12556, name = "Frost Armor", desc = "Buffed with Frost Armor."},
            },
            mechanics = {
                "Pick up the Frost Spectres at 55% and 30%.",
                "Interrupt Frostbolt; melee expect roots.",
            },
            loot = {
                {id = 10762, name = "Robes of the Lich", slot = "Chest, Cloth", quality = 3, icon = "inv_chest_cloth_17", rate = "29.52%"},
                {id = 10765, name = "Bonefingers", slot = "Hands, Leather", quality = 3, icon = "inv_gauntlets_09", note = "AtlasLoot gives no rate."},
                {id = 10764, name = "Deathchill Armor", slot = "Chest, Mail", quality = 3, icon = "inv_chest_plate12", rate = "24.24%"},
                {id = 10763, name = "Icemetal Barbute", slot = "Head, Plate", quality = 3, icon = "inv_helmet_13", rate = "28.66%"},
                {id = 10761, name = "Coldrage Dagger", slot = "One-Hand, Dagger", quality = 3, icon = "inv_sword_34", rate = "13.89%"},
                {
                    id = 10420,
                    name = "Skull of the Coldbringer",
                    slot = "Quest Item - Bring the End",
                    quality = 1,
                    icon = "inv_misc_bone_humanskull_01",
                    rate = "100%",
                    note = "Horde quest Bring the End.",
                },
            },
        },
        {
            name = "Plaguemaw the Rotting",
            npc = 7356,
            level = "40 Elite",
            optional = true,
            portrait = P .. "PlaguemawTheRotting",
            summary = "Last wave of the Extinguishing the Idol event [7] (AzerothCore spawns it on the eighth spawner).",
            abilities = {
                {spell = 12946, name = "Putrid Stench", tag = "SILENCE", desc = "Players nearby lose 50 Strength and Agility and cannot cast for 10 sec."},
            },
            mechanics = {
                "Only appears during Belnistrasz's idol event.",
                "Keep him on the tank and off Belnistrasz.",
            },
            loot = {
                {id = 10760, name = "Swine Fists", slot = "Hands, Leather", quality = 3, icon = "inv_gauntlets_23", rate = "58.15%"},
                {id = 10766, name = "Plaguerot Sprig", slot = "Ranged, Wand", quality = 3, icon = "inv_wand_03", rate = "29.98%"},
            },
        },
    },
    quests = {
        {
            id = 6626,
            name = "A Host of Evil",
            faction = "Both",
            level = 35,
            minLevel = 28,
            prerequisites = "None.",
            where = "Outside, in front of the dungeon entrance.",
            turnin = "Myriam Moonsinger",
            turninLocation = "The Barrens (49.0, 94.8)",
            rewards = {money = 7500},
            giver = "Myriam Moonsinger",
            giverLocation = "The Barrens (49.0, 94.8)",
            objective = "Kill 8 Razorfen Battleguard, 8 Razorfen Thornweavers, and 8 Death's Head Cultists and return to Myriam Moonsinger near the entrance to Razorfen Downs.",
        },
        {
            id = 3525,
            name = "Extinguishing the Idol",
            faction = "Both",
            level = 37,
            minLevel = 32,
            prerequisites = "Scourge of the Downs (3523) from Belnistrasz [2] (you agree to help him).",
            where = "Escort Belnistrasz to the idol and protect him for about 5 minutes. Waves of Withered Battle Boars, Death's Head Geomancers and Withered Quilguards attack; Plaguemaw the Rotting comes last.",
            turnin = "Belnistrasz's Brazier",
            turninLocation = "Razorfen Downs (in front of the idol)",
            chain = {
                {id = 3523, name = "Scourge of the Downs", text = "Belnistrasz [2]."},
                {id = 3525, name = "Extinguishing the Idol", text = "(this quest)"},
            },
            rewards = {
                items = {
                    {id = 10710, name = "Dragonclaw Ring", slot = "Finger", quality = 3, icon = "inv_jewelry_ring_04"},
                },
            },
            giver = "Belnistrasz",
            giverLocation = "Razorfen Downs [2]",
            objective = "Escort Belnistrasz to the Quilboar's idol in Razorfen Downs. Protect Belnistrasz while he performs the ritual to shut down the idol.",
        },
        {
            id = 3636,
            name = "Bring the Light",
            faction = "Alliance",
            level = 37,
            minLevel = 32,
            prerequisites = "None.",
            where = "Amnennar the Coldbringer [6].",
            turnin = "Archbishop Benedictus",
            turninLocation = "Stormwind - Cathedral of Light (39.6, 27.4)",
            rewards = {
                reputation = "Stormwind",
                items = {
                    {id = 10823, name = "Vanquisher's Sword", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_35"},
                    {id = 10824, name = "Amberglow Talisman", slot = "Neck", quality = 3, icon = "inv_jewelry_necklace_07"},
                },
            },
            notes = "AtlasQuest: level 42, min 39; AzerothCore: level 37, min 32.",
            giver = "Archbishop Benedictus",
            giverLocation = "Stormwind - Cathedral of Light (39.6, 27.4)",
            objective = "Archbishop Benedictus wants you to slay Amnennar the Coldbringer in Razorfen Downs.",
        },
        {
            id = 14353,
            name = "An Unholy Alliance",
            faction = "Horde",
            level = 36,
            minLevel = 28,
            giver = "Bragor Bloodfist",
            giverLocation = "Undercity",
            objective = "Bring Ambassador Malcin's Head to Bragor Bloodfist.",
            prerequisites = "An Unholy Alliance (14352), started by the Small Scroll from Charlga Razorflank (Razorfen Kraul).",
            requiredItems = {
                {id = 17009, name = "Ambassador Malcin's Head", where = "Ambassador Malcin, outside the dungeon (The Barrens 48.0, 92.4)"},
            },
            turnin = "Bragor Bloodfist",
            turninLocation = "Undercity",
            chain = {
                {id = 14352, name = "An Unholy Alliance", text = "Small Scroll -> Bragor Bloodfist."},
                {id = 14353, name = "An Unholy Alliance", text = "(this quest)"},
            },
            rewards = {
                money = 2000,
                choice = {
                    {id = 17039, name = "Skullbreaker", slot = "One-Hand, Mace", quality = 2, icon = "inv_misc_bone_dwarfskull_01"},
                    {id = 17042, name = "Nail Spitter", slot = "Gun", quality = 2, icon = "inv_weapon_rifle_01"},
                    {id = 17043, name = "Zealot's Robe", slot = "Chest, Cloth", quality = 2, icon = "inv_chest_cloth_06"},
                },
            },
            notes = "AtlasQuest lists the older quest 6521 (Varimathras); AzerothCore uses 14352/14353 and Bragor Bloodfist.",
        },
        {
            id = 3341,
            name = "Bring the End",
            faction = "Horde",
            level = 37,
            minLevel = 33,
            prerequisites = "None.",
            requiredItems = {
                {id = 10420, name = "Skull of the Coldbringer", where = "Amnennar the Coldbringer [6]"},
            },
            turnin = "Andrew Brownell",
            turninLocation = "Undercity - The Magic Quarter (74.0, 32.8)",
            rewards = {
                reputation = "Undercity",
                items = {
                    {id = 10823, name = "Vanquisher's Sword", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_35"},
                    {id = 10824, name = "Amberglow Talisman", slot = "Neck", quality = 3, icon = "inv_jewelry_necklace_07"},
                },
            },
            notes = "AtlasQuest: level 42, min 37; AzerothCore: level 37, min 33.",
            giver = "Andrew Brownell",
            giverLocation = "Undercity - The Magic Quarter (74.0, 32.8)",
            objective = "Andrew Brownell wants you to kill Amnennar the Coldbringer and return his skull.",
        },
    },
    preparation = {
        {
            title = "Level",
            lines = {"Dungeon level 33-42; entry from level 25 (Atlas)."},
        },
        {
            title = "Access",
            lines = {
                "Entrance in the far south of the Barrens, next to Razorfen Kraul. No key.",
            },
        },
        {
            title = "Events",
            lines = {
                "Tuten'kash [1]: ring the gong; three waves come, Tuten'kash last.",
                "Extinguishing the Idol: talk to Belnistrasz [2] and guard him at the idol for about 5 minutes.",
                "Henry Stern [2] teaches Goldthorn Tea and Major Troll's Blood Potion through gossip (AzerothCore). AtlasLoot lists Recipe: Mighty Troll's Blood Potion under him instead.",
            },
        },
        {
            title = "Consumables",
            lines = {"Food, water and healing / mana potions."},
        },
        {
            title = "Server rules (restored Vanilla AI)",
            lines = {
                "Frozen Souls silence and Freezing Spirits root: casters keep distance.",
                "Necromancers and Skeletal Summoners add extra skeletons.",
                "Many Death's Head and quilboar mobs flee for help at 15% health.",
            },
        },
    },
})
