-- Scarlet Monastery: Armory (Vanilla batch 3, v0.3.3)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/SMArmory.blp, SMEnt.blp + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (SMHerod, SMTrash), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/dungeon_scarlet_monastery.sql smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    id = "smarm",
    name = "Scarlet Monastery: Armory",
    level = "33-40",
    location = "Tirisfal Glades",
    tag = "Dungeon",
    minLevel = "20",
    art = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenMonastery",
    crop = {0.04, 0.96, 0.29, 0.73},
    fallbackCrop = {0.0, 1.0, 0.25, 0.7},
    artFallback = SDJ.MAPS .. "SMArmory",
    maps = {
        {
            name = "SM: Armory",
            texture = SDJ.MAPS .. "SMArmory",
            coords = {0, 1, 0, 1},
            legend = {
                {"", "Key: The Scarlet Key"},
                {"A", "Entrance", "blue"},
                {"1", "Herod <The Scarlet Champion>"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
        {
            name = "Scarlet Monastery (Entrance)",
            texture = SDJ.MAPS .. "SMEnt",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"B", "Graveyard", "blue"},
                {"C", "Cathedral", "blue"},
                {"D", "Armory", "blue"},
                {"E", "Library", "blue"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
    },
    trash = {
        mobs = {
            {
                name = "Scarlet Protector",
                npc = 4292,
                level = "36-37 Elite",
                priority = 1,
                abilities = {
                    {spell = 15493, name = "Holy Light", tag = "HEAL", desc = "Heals an injured ally."},
                    {spell = 8258, name = "Devotion Aura", desc = "Armour aura for its allies."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Interrupt Holy Light.",
            },
            {
                name = "Scarlet Evoker",
                npc = 4289,
                level = "36-37 Elite",
                priority = 1,
                abilities = {
                    {spell = 8422, name = "Flamestrike", tag = "AOE", desc = "Fire on a target area."},
                    {spell = 9053, name = "Fireball", desc = "Fire nuke."},
                    {spell = 2601, name = "Fire Shield III", desc = "Fire damage to attackers nearby."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Conjuror",
                npc = 4297,
                level = "35-36 Elite",
                priority = 2,
                abilities = {
                    {spell = 8985, name = "Summon Fire Elemental", tag = "SUMMON", desc = "Has a Fire Elemental out."},
                    {spell = 9053, name = "Fireball", desc = "Fire nuke."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Guardsman",
                npc = 4290,
                level = "36-37 Elite",
                priority = 3,
                abilities = {
                    {spell = 676, name = "Disarm", tag = "DISARM", desc = "Disarms the tank."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Defender",
                npc = 4298,
                level = "37-38 Elite",
                priority = 3,
                abilities = {
                    {spell = 3639, name = "Improved Blocking", desc = "Block chance +85% for 6 sec."},
                    {spell = 11972, name = "Shield Bash", tag = "INTERRUPT", desc = "Interrupts spellcasting."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Myrmidon",
                npc = 4295,
                level = "37-38 Elite",
                priority = 3,
                abilities = {
                    {spell = 8269, name = "Frenzy", tag = "ENRAGE", desc = "Enrages at 30%."},
                },
                note = "",
            },
            {
                name = "Scarlet Soldier",
                npc = 4286,
                level = "35-36 Elite",
                priority = 3,
                abilities = {
                    {spell = 3639, name = "Improved Blocking", desc = "Block chance +85% for 6 sec."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
        },
        loot = {
            {id = 7728, name = "Beguiler Robes", slot = "Chest, Cloth", quality = 3, icon = "inv_chest_cloth_25", rate = "0.01%"},
            {id = 7755, name = "Flintrock Shoulders", slot = "Shoulder, Leather", quality = 3, icon = "inv_shoulder_13", rate = "0.00%"},
            {id = 7727, name = "Watchman Pauldrons", slot = "Shoulder, Leather", quality = 3, icon = "inv_shoulder_23", rate = "0.01%"},
            {id = 7760, name = "Warchief Kilt", slot = "Legs, Leather", quality = 3, icon = "inv_pants_06", rate = "0.00%"},
            {id = 7754, name = "Harbinger Boots", slot = "Feet, Leather", quality = 3, icon = "inv_boots_05", rate = "0.01%"},
            {id = 5819, name = "Sunblaze Coif", slot = "Head, Mail", quality = 3, icon = "inv_helmet_03", rate = "0.01%"},
            {id = 7759, name = "Archon Chestpiece", slot = "Chest, Mail", quality = 3, icon = "inv_chest_chain_11", rate = "0.00%"},
            {id = 10328, name = "Scarlet Chestpiece", slot = "Chest, Mail", quality = 3, icon = "inv_chest_chain_07", rate = "0.3%"},
            {id = 10332, name = "Scarlet Boots", slot = "Feet, Mail", quality = 3, icon = "inv_boots_02", rate = "0.1%"},
            {id = 2262, name = "Mark of Kern", slot = "Finger", quality = 3, icon = "inv_jewelry_ring_15", rate = "0.01%"},
            {id = 1992, name = "Swampchill Fetish", slot = "Held In Off-hand", quality = 3, icon = "inv_misc_bone_orcskull_01", rate = "0.00%"},
            {id = 10333, name = "Scarlet Wristguards", slot = "Wrist, Mail", quality = 2, icon = "inv_bracer_03", rate = "1.6%"},
            {id = 10331, name = "Scarlet Gauntlets", slot = "Hands, Mail", quality = 2, icon = "inv_gauntlets_19", rate = "1.7%"},
            {id = 10329, name = "Scarlet Belt", slot = "Waist, Mail", quality = 2, icon = "inv_belt_06", rate = "1.6%"},
            {id = 5756, name = "Sliverblade", slot = "One-Hand, Dagger", quality = 3, icon = "inv_weapon_shortblade_24", rate = "0.01%"},
            {id = 8225, name = "Tainted Pierce", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_30", rate = "0.01%"},
            {id = 8226, name = "The Butcher", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_18", rate = "0.01%"},
            {id = 7786, name = "Headsplitter", slot = "One-Hand, Axe", quality = 3, icon = "inv_axe_14", rate = "0.01%"},
            {id = 7761, name = "Steelclaw Reaver", slot = "One-Hand, Axe", quality = 3, icon = "inv_axe_06", rate = "0.01%"},
            {id = 7753, name = "Bloodspiller", slot = "Two-Hand, Axe", quality = 3, icon = "inv_axe_10", rate = "0.01%"},
            {id = 7752, name = "Dreamslayer", slot = "One-Hand, Mace", quality = 3, icon = "inv_hammer_17", rate = "0.01%"},
            {id = 7736, name = "Fight Club", slot = "One-Hand, Mace", quality = 3, icon = "inv_mace_11", rate = "0.00%"},
            {id = 7730, name = "Cobalt Crusher", slot = "Two-Hand, Mace", quality = 3, icon = "inv_hammer_04", rate = "0.01%"},
            {id = 7758, name = "Ruthless Shiv", slot = "Two-Hand, Polearm", quality = 3, icon = "inv_spear_08", rate = "0.00%"},
            {id = 7757, name = "Windweaver Staff", slot = "Two-Hand, Staff", quality = 3, icon = "inv_wand_07", rate = "0.01%"},
            {id = 7787, name = "Resplendent Guardian", slot = "Off Hand, Shield", quality = 3, icon = "inv_shield_02", rate = "0.01%"},
            {id = 7729, name = "Chesterfall Musket", slot = "Gun", quality = 3, icon = "inv_weapon_rifle_06", rate = "0.01%"},
            {
                id = 5805,
                name = "Heart of Zeal",
                slot = "Quest Item - Hearts of Zeal",
                quality = 1,
                icon = "inv_misc_organ_02",
                note = "Horde quest drop from Scarlet Monastery mobs (AzerothCore: 80% trash, 2% bosses).",
            },
        },
        lootNote = "AtlasLoot \"SMTrash\" is one shared table for all four Scarlet Monastery wings (rates as listed by AtlasLoot, some shown as 0.00%). Heart of Zeal comes from the AzerothCore loot tables.",
    },
    bosses = {
        {
            name = "Herod",
            subname = "The Scarlet Champion",
            npc = 3975,
            level = "40 Elite",
            portrait = P .. "Herod",
            summary = "Scarlet champion in the training hall [1]. When he dies a group of Scarlet Trainees rushes in.",
            abilities = {
                {spell = 15496, name = "Cleave", desc = "Hits the target and the nearest ally."},
                {spell = 8989, name = "Whirlwind", tag = "AOE", desc = "10 sec channel hitting everyone nearby."},
                {spell = 8269, name = "Frenzy", tag = "ENRAGE", desc = "Enrages at 50% health."},
            },
            mechanics = {
                "Everyone except the tank runs out during Whirlwind.",
                "After his death, be ready for the Scarlet Trainees (AzerothCore creature group).",
            },
            loot = {
                {id = 7719, name = "Raging Berserker's Helm", slot = "Head, Mail", quality = 3, icon = "inv_helmet_25", rate = "30.62%"},
                {id = 7718, name = "Herod's Shoulder", slot = "Shoulder, Mail", quality = 3, icon = "inv_shoulder_01", rate = "30.82%"},
                {id = 10330, name = "Scarlet Leggings", slot = "Legs, Mail", quality = 3, icon = "inv_pants_03", rate = "12.75%"},
                {id = 7717, name = "Ravager", slot = "Two-Hand, Axe", quality = 3, icon = "inv_weapon_halberd_05", rate = "12.86%"},
                {
                    id = 23192,
                    name = "Tabard of the Scarlet Crusade",
                    slot = "Tabard",
                    quality = 2,
                    icon = "inv_misc_cape_18",
                    rate = "0.4%",
                    note = "Dropped by the Scarlet Trainees that appear when Herod dies.",
                },
            },
            lootNote = "AzerothCore's comment says Enrage at 40%; the event triggers at 50%.",
        },
    },
    quests = {
        {
            id = 1053,
            name = "In the Name of the Light",
            faction = "Alliance",
            level = 40,
            minLevel = 34,
            prerequisites = "Down the Scarlet Path (1052), after Brother Anton (6141) and Down the Scarlet Path (261). The chain starts at Brother Crowley (Stormwind - Cathedral of Light 42.4, 24.4).",
            where = "Herod is in this wing [1]. Kill targets: Whitemane and Mograine (Cathedral [2]), Herod (Armory [1]), Houndmaster Loksey (Library [1]).",
            turnin = "Raleigh the Devout",
            turninLocation = "Hillsbrad Foothills - Southshore (51.4, 58.4)",
            chain = {
                {id = 6141, name = "Brother Anton", text = "Brother Crowley -> Brother Anton."},
                {id = 261, name = "Down the Scarlet Path", text = "30 Undead Ravagers."},
                {id = 1052, name = "Down the Scarlet Path", text = "Letter of Commendation -> Raleigh the Devout."},
                {id = 1053, name = "In the Name of the Light", text = "(this quest)"},
            },
            rewards = {
                reputation = "Stormwind",
                choice = {
                    {id = 6829, name = "Sword of Serenity", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_27"},
                    {id = 6830, name = "Bonebiter", slot = "Two-Hand, Axe", quality = 3, icon = "inv_axe_04"},
                    {id = 6831, name = "Black Menace", slot = "One-Hand, Dagger", quality = 3, icon = "inv_sword_13"},
                    {id = 11262, name = "Orb of Lorica", slot = "Held In Off-hand", quality = 3, icon = "inv_misc_orb_01"},
                },
            },
            notes = "Spans three wings: Library, Armory and Cathedral.",
            giver = "Raleigh the Devout",
            giverLocation = "Hillsbrad Foothills - Southshore (51.4, 58.4)",
            objective = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Raleigh the Devout in Southshore.",
        },
        {
            id = 1113,
            name = "Hearts of Zeal",
            faction = "Horde",
            level = 33,
            minLevel = 30,
            prerequisites = "Going, Going, Guano! (1109, Razorfen Kraul).",
            requiredItems = {
                {id = 5805, name = "Heart of Zeal", where = "Any Scarlet Monastery mob, including those outside near the portals (x20)"},
            },
            turnin = "Master Apothecary Faranell",
            turninLocation = "Undercity - The Apothecarium (48.6, 69.4)",
            rewards = {reputation = "Undercity"},
            notes = "Hearts of Zeal drop in every wing.",
            giver = "Master Apothecary Faranell",
            giverLocation = "Undercity - The Apothecarium (48.6, 69.4)",
            objective = "Master Apothecary Faranell in the Undercity wants 20 Hearts of Zeal.",
        },
        {
            id = 1048,
            name = "Into The Scarlet Monastery",
            faction = "Horde",
            level = 42,
            minLevel = 30,
            prerequisites = "None.",
            where = "Herod is in this wing [1]. Kill targets: Whitemane and Mograine (Cathedral [2]), Herod (Armory [1]), Houndmaster Loksey (Library [1]).",
            turnin = "Varimathras",
            turninLocation = "Undercity - Royal Quarter (56.2, 92.6)",
            rewards = {
                reputation = "Undercity",
                choice = {
                    {id = 6802, name = "Sword of Omen", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_19"},
                    {id = 6803, name = "Prophetic Cane", slot = "Held In Off-hand", quality = 3, icon = "inv_staff_01"},
                    {id = 10711, name = "Dragon's Blood Necklace", slot = "Neck", quality = 3, icon = "inv_jewelry_necklace_02"},
                },
            },
            notes = "Spans three wings: Library, Armory and Cathedral. AtlasQuest gives minimum level 33; AzerothCore requires 30.",
            giver = "Varimathras",
            giverLocation = "Undercity - Royal Quarter (56.2, 92.6)",
            objective = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Varimathras in the Undercity.",
        },
    },
    preparation = {
        {
            title = "Level",
            lines = {"Wing level 33-40; entry from level 20 (Atlas)."},
        },
        {
            title = "Access & keys",
            lines = {
                "Scarlet Monastery is in north-eastern Tirisfal Glades; the four wings have separate instance portals (entrance map).",
                "The Scarlet Key drops from Doan's Strongbox after Arcanist Doan (Library [2]). It opens the Armory and Cathedral doors (AzerothCore lock 299 on both doors; Atlas lists the key for both wings).",
            },
        },
        {
            title = "Consumables",
            lines = {"Food, water and healing / mana potions."},
        },
        {
            title = "Server rules (restored Vanilla AI)",
            lines = {
                "Protectors heal, Evokers cast Flamestrike.",
                "Herod whirlwinds; his death brings a wave of Scarlet Trainees.",
                "Most Scarlet humanoids flee for help at 15% health: finish runners before they pull more.",
            },
        },
    },
})
