-- Scarlet Monastery: Cathedral (Vanilla batch 3, v0.3.3)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/SMCathedral.blp, SMEnt.blp + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (SMCathedral, SMTrash), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/dungeon_scarlet_monastery.sql smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    id = "smcat",
    name = "Scarlet Monastery: Cathedral",
    level = "36-42",
    location = "Tirisfal Glades",
    tag = "Dungeon",
    minLevel = "20",
    art = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenMonastery",
    crop = {0.04, 0.96, 0.29, 0.73},
    fallbackCrop = {0.0, 1.0, 0.25, 0.7},
    artFallback = SDJ.MAPS .. "SMCathedral",
    maps = {
        {
            name = "SM: Cathedral",
            texture = SDJ.MAPS .. "SMCathedral",
            coords = {0, 1, 0, 1},
            legend = {
                {"", "Key: The Scarlet Key"},
                {"A", "Entrance", "blue"},
                {"1", "High Inquisitor Fairbanks"},
                {"2", "Scarlet Commander Mograine"},
                {"", "High Inquisitor Whitemane"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
        {
            name = "Scarlet Monastery (Entrance)",
            texture = SDJ.MAPS .. "SMEnt",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"B", "Graveyard", "blue"},
                {"C", "Cathedral", "blue"},
                {"D", "Armory", "blue"},
                {"E", "Library", "blue"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
    },
    trash = {
        mobs = {
            {
                name = "Scarlet Abbot",
                npc = 4303,
                level = "39-40 Elite",
                priority = 1,
                abilities = {
                    {spell = 6064, name = "Heal", tag = "HEAL", desc = "Heals an injured ally."},
                    {spell = 8362, name = "Renew", tag = "HEAL", desc = "Heal over time on an ally below 50%."},
                    {spell = 8269, name = "Frenzy", tag = "ENRAGE", desc = "Enrages at 30%."},
                },
                note = "Interrupt Heal.",
            },
            {
                name = "Scarlet Chaplain",
                npc = 4299,
                level = "34-36 Elite",
                priority = 1,
                abilities = {
                    {spell = 6066, name = "Power Word: Shield", tag = "HEAL", desc = "Shields an ally."},
                    {spell = 8362, name = "Renew", tag = "HEAL", desc = "Heal over time on an ally."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Sorcerer",
                npc = 4294,
                level = "37-38 Elite",
                priority = 1,
                abilities = {
                    {spell = 8364, name = "Blizzard", tag = "AOE", desc = "Frost damage in an area for 10 sec."},
                    {spell = 6146, name = "Slow", tag = "DEBUFF", desc = "Movement -60%, attack speed -54% for 15 sec."},
                    {spell = 9672, name = "Frostbolt", desc = "Frost nuke."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Wizard",
                npc = 4300,
                level = "38-39 Elite",
                priority = 2,
                abilities = {
                    {spell = 8439, name = "Arcane Explosion", tag = "AOE", desc = "Arcane damage to nearby enemies."},
                    {spell = 2601, name = "Fire Shield III", desc = "Fire damage to attackers nearby."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Champion",
                npc = 4302,
                level = "39-40 Elite",
                priority = 2,
                abilities = {
                    {spell = 17143, name = "Holy Strike", desc = "Holy damage on its next hit."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Centurion",
                npc = 4301,
                level = "38-39 Elite",
                priority = 3,
                abilities = {
                    {spell = 6192, name = "Battle Shout", desc = "Raises allies' attack power."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Monk / Myrmidon / Defender",
                npc = 4540,
                level = "35-36 Elite",
                priority = 3,
                abilities = {
                    {spell = 11978, name = "Kick", tag = "INTERRUPT", desc = "Interrupts a spell (Monk)."},
                    {spell = 8269, name = "Frenzy", tag = "ENRAGE", desc = "Enrages at 30% (Myrmidon)."},
                    {spell = 11972, name = "Shield Bash", tag = "INTERRUPT", desc = "Interrupts spellcasting (Defender)."},
                },
                note = "",
            },
        },
        loot = {
            {id = 7728, name = "Beguiler Robes", slot = "Chest, Cloth", quality = 3, icon = "inv_chest_cloth_25", rate = "0.01%"},
            {id = 7755, name = "Flintrock Shoulders", slot = "Shoulder, Leather", quality = 3, icon = "inv_shoulder_13", rate = "0.00%"},
            {id = 7727, name = "Watchman Pauldrons", slot = "Shoulder, Leather", quality = 3, icon = "inv_shoulder_23", rate = "0.01%"},
            {id = 7760, name = "Warchief Kilt", slot = "Legs, Leather", quality = 3, icon = "inv_pants_06", rate = "0.00%"},
            {id = 7754, name = "Harbinger Boots", slot = "Feet, Leather", quality = 3, icon = "inv_boots_05", rate = "0.01%"},
            {id = 5819, name = "Sunblaze Coif", slot = "Head, Mail", quality = 3, icon = "inv_helmet_03", rate = "0.01%"},
            {id = 7759, name = "Archon Chestpiece", slot = "Chest, Mail", quality = 3, icon = "inv_chest_chain_11", rate = "0.00%"},
            {id = 10328, name = "Scarlet Chestpiece", slot = "Chest, Mail", quality = 3, icon = "inv_chest_chain_07", rate = "0.3%"},
            {id = 10332, name = "Scarlet Boots", slot = "Feet, Mail", quality = 3, icon = "inv_boots_02", rate = "0.1%"},
            {id = 2262, name = "Mark of Kern", slot = "Finger", quality = 3, icon = "inv_jewelry_ring_15", rate = "0.01%"},
            {id = 1992, name = "Swampchill Fetish", slot = "Held In Off-hand", quality = 3, icon = "inv_misc_bone_orcskull_01", rate = "0.00%"},
            {id = 10333, name = "Scarlet Wristguards", slot = "Wrist, Mail", quality = 2, icon = "inv_bracer_03", rate = "1.6%"},
            {id = 10331, name = "Scarlet Gauntlets", slot = "Hands, Mail", quality = 2, icon = "inv_gauntlets_19", rate = "1.7%"},
            {id = 10329, name = "Scarlet Belt", slot = "Waist, Mail", quality = 2, icon = "inv_belt_06", rate = "1.6%"},
            {id = 5756, name = "Sliverblade", slot = "One-Hand, Dagger", quality = 3, icon = "inv_weapon_shortblade_24", rate = "0.01%"},
            {id = 8225, name = "Tainted Pierce", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_30", rate = "0.01%"},
            {id = 8226, name = "The Butcher", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_18", rate = "0.01%"},
            {id = 7786, name = "Headsplitter", slot = "One-Hand, Axe", quality = 3, icon = "inv_axe_14", rate = "0.01%"},
            {id = 7761, name = "Steelclaw Reaver", slot = "One-Hand, Axe", quality = 3, icon = "inv_axe_06", rate = "0.01%"},
            {id = 7753, name = "Bloodspiller", slot = "Two-Hand, Axe", quality = 3, icon = "inv_axe_10", rate = "0.01%"},
            {id = 7752, name = "Dreamslayer", slot = "One-Hand, Mace", quality = 3, icon = "inv_hammer_17", rate = "0.01%"},
            {id = 7736, name = "Fight Club", slot = "One-Hand, Mace", quality = 3, icon = "inv_mace_11", rate = "0.00%"},
            {id = 7730, name = "Cobalt Crusher", slot = "Two-Hand, Mace", quality = 3, icon = "inv_hammer_04", rate = "0.01%"},
            {id = 7758, name = "Ruthless Shiv", slot = "Two-Hand, Polearm", quality = 3, icon = "inv_spear_08", rate = "0.00%"},
            {id = 7757, name = "Windweaver Staff", slot = "Two-Hand, Staff", quality = 3, icon = "inv_wand_07", rate = "0.01%"},
            {id = 7787, name = "Resplendent Guardian", slot = "Off Hand, Shield", quality = 3, icon = "inv_shield_02", rate = "0.01%"},
            {id = 7729, name = "Chesterfall Musket", slot = "Gun", quality = 3, icon = "inv_weapon_rifle_06", rate = "0.01%"},
            {
                id = 5805,
                name = "Heart of Zeal",
                slot = "Quest Item - Hearts of Zeal",
                quality = 1,
                icon = "inv_misc_organ_02",
                note = "Horde quest drop from Scarlet Monastery mobs (AzerothCore: 80% trash, 2% bosses).",
            },
        },
        lootNote = "AtlasLoot \"SMTrash\" is one shared table for all four Scarlet Monastery wings (rates as listed by AtlasLoot, some shown as 0.00%). Heart of Zeal comes from the AzerothCore loot tables.",
    },
    bosses = {
        {
            name = "High Inquisitor Fairbanks",
            npc = 4542,
            level = "40 Elite",
            portrait = P .. "HighInquisitorFairbanks",
            summary = "High Inquisitor at the end of the courtyard hall [1].",
            abilities = {
                {spell = 8282, name = "Curse of Blood", tag = "CURSE", desc = "Increases physical damage taken."},
                {spell = 15090, name = "Dispel Magic", tag = "DISPEL", desc = "Dispels a buff or debuff."},
                {spell = 11647, name = "Power Word: Shield", desc = "Shields himself."},
                {spell = 12039, name = "Heal", tag = "HEAL", desc = "Heals himself."},
            },
            mechanics = {"Interrupt Heal; dispel or burn through his shield."},
            loot = {
                {id = 19507, name = "Inquisitor's Shawl", slot = "Shoulder, Cloth", quality = 3, icon = "inv_shoulder_27", rate = "15.94%"},
                {id = 19508, name = "Branded Leather Bracers", slot = "Wrist, Leather", quality = 3, icon = "inv_bracer_11", rate = "16.17%"},
                {id = 19509, name = "Dusty Mail Boots", slot = "Feet, Mail", quality = 3, icon = "inv_boots_chain_02", rate = "17.24%"},
            },
        },
        {
            name = "Scarlet Commander Mograine",
            npc = 3976,
            level = "42 Elite",
            portrait = P .. "ScarletCommanderMograine",
            summary = "Commander of the Scarlet Crusade in the chapel [2]. Pulling him brings the whole chapel.",
            abilities = {
                {spell = 8990, name = "Retribution Aura", desc = "Holy damage to anyone who hits him or his allies."},
                {spell = 14518, name = "Crusader Strike", desc = "Melee hit that increases Holy damage taken."},
                {spell = 5589, name = "Hammer of Justice", tag = "STUN", desc = "Stuns a target within 10 yd for 5 sec."},
            },
            mechanics = {
                "When Mograine is engaged, the Scarlet monks, abbots, champions, centurions, wizards and chaplains within 80 yd join the fight (AzerothCore instance script). Clear the chapel first.",
                "He cannot drop below 1 HP: at that point he feigns death and Whitemane enters through the door behind him.",
            },
            loot = {
                {id = 7724, name = "Gauntlets of Divinity", slot = "Hands, Mail", quality = 3, icon = "inv_gauntlets_19", rate = "17.49%"},
                {id = 10330, name = "Scarlet Leggings", slot = "Legs, Mail", quality = 3, icon = "inv_pants_03", rate = "12.95%"},
                {id = 7723, name = "Mograine's Might", slot = "Two-Hand, Mace", quality = 3, icon = "inv_mace_13", rate = "17.13%"},
                {id = 7726, name = "Aegis of the Scarlet Commander", slot = "Off Hand, Shield", quality = 3, icon = "inv_shield_05", rate = "38.37%"},
            },
        },
        {
            name = "High Inquisitor Whitemane",
            npc = 3977,
            level = "42 Elite",
            portrait = P .. "HighInquisitorWhitemane",
            summary = "High Inquisitor [2]; comes to Mograine's aid.",
            abilities = {
                {spell = 9481, name = "Holy Smite", desc = "Holy nuke, cast constantly."},
                {spell = 22187, name = "Power Word: Shield", tag = "HEAL", desc = "Shields an ally."},
                {spell = 9256, name = "Deep Sleep", tag = "CC", desc = "At 50%: puts nearby players to sleep for up to 10 sec."},
                {spell = 9232, name = "Scarlet Resurrection", desc = "Resurrects Mograine."},
                {spell = 14515, name = "Dominate Mind", tag = "CC", desc = "After the resurrection: takes control of a player."},
                {spell = 12039, name = "Heal", tag = "HEAL", desc = "After the resurrection: heals an ally below 75%."},
            },
            mechanics = {
                "At 50% she casts Deep Sleep, then resurrects Mograine; he gets up (Lay on Hands on her) and both fight together.",
                "Save cooldowns for the second half: kill Mograine again, then Whitemane, or burn her while controlling him.",
                "She cannot drop below 1 HP until after the resurrection.",
            },
            loot = {
                {id = 7720, name = "Whitemane's Chapeau", slot = "Head, Cloth", quality = 3, icon = "inv_helmet_12", rate = "34.01%"},
                {id = 7722, name = "Triune Amulet", slot = "Neck", quality = 3, icon = "inv_jewelry_amulet_01", rate = "33.23%"},
                {id = 7721, name = "Hand of Righteousness", slot = "Main Hand, Mace", quality = 3, icon = "inv_hammer_02", rate = "18.32%"},
                {
                    id = 20976,
                    name = "Design: Citrine Pendant of Golden Healing",
                    slot = "Recipe",
                    quality = 2,
                    icon = "inv_scroll_06",
                    rate = "100%",
                    note = "AtlasLoot: 100%; AzerothCore: 10%.",
                },
            },
        },
    },
    quests = {
        {
            id = 1053,
            name = "In the Name of the Light",
            faction = "Alliance",
            level = 40,
            minLevel = 34,
            prerequisites = "Down the Scarlet Path (1052), after Brother Anton (6141) and Down the Scarlet Path (261). The chain starts at Brother Crowley (Stormwind - Cathedral of Light 42.4, 24.4).",
            where = "Whitemane and Mograine are in this wing [2]. Kill targets: Whitemane and Mograine (Cathedral [2]), Herod (Armory [1]), Houndmaster Loksey (Library [1]).",
            turnin = "Raleigh the Devout",
            turninLocation = "Hillsbrad Foothills - Southshore (51.4, 58.4)",
            chain = {
                {id = 6141, name = "Brother Anton", text = "Brother Crowley -> Brother Anton."},
                {id = 261, name = "Down the Scarlet Path", text = "30 Undead Ravagers."},
                {id = 1052, name = "Down the Scarlet Path", text = "Letter of Commendation -> Raleigh the Devout."},
                {id = 1053, name = "In the Name of the Light", text = "(this quest)"},
            },
            rewards = {
                reputation = "Stormwind",
                choice = {
                    {id = 6829, name = "Sword of Serenity", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_27"},
                    {id = 6830, name = "Bonebiter", slot = "Two-Hand, Axe", quality = 3, icon = "inv_axe_04"},
                    {id = 6831, name = "Black Menace", slot = "One-Hand, Dagger", quality = 3, icon = "inv_sword_13"},
                    {id = 11262, name = "Orb of Lorica", slot = "Held In Off-hand", quality = 3, icon = "inv_misc_orb_01"},
                },
            },
            notes = "Spans three wings: Library, Armory and Cathedral.",
            giver = "Raleigh the Devout",
            giverLocation = "Hillsbrad Foothills - Southshore (51.4, 58.4)",
            objective = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Raleigh the Devout in Southshore.",
        },
        {
            id = 1113,
            name = "Hearts of Zeal",
            faction = "Horde",
            level = 33,
            minLevel = 30,
            prerequisites = "Going, Going, Guano! (1109, Razorfen Kraul).",
            requiredItems = {
                {id = 5805, name = "Heart of Zeal", where = "Any Scarlet Monastery mob, including those outside near the portals (x20)"},
            },
            turnin = "Master Apothecary Faranell",
            turninLocation = "Undercity - The Apothecarium (48.6, 69.4)",
            rewards = {reputation = "Undercity"},
            notes = "Hearts of Zeal drop in every wing.",
            giver = "Master Apothecary Faranell",
            giverLocation = "Undercity - The Apothecarium (48.6, 69.4)",
            objective = "Master Apothecary Faranell in the Undercity wants 20 Hearts of Zeal.",
        },
        {
            id = 1048,
            name = "Into The Scarlet Monastery",
            faction = "Horde",
            level = 42,
            minLevel = 30,
            prerequisites = "None.",
            where = "Whitemane and Mograine are in this wing [2]. Kill targets: Whitemane and Mograine (Cathedral [2]), Herod (Armory [1]), Houndmaster Loksey (Library [1]).",
            turnin = "Varimathras",
            turninLocation = "Undercity - Royal Quarter (56.2, 92.6)",
            rewards = {
                reputation = "Undercity",
                choice = {
                    {id = 6802, name = "Sword of Omen", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_19"},
                    {id = 6803, name = "Prophetic Cane", slot = "Held In Off-hand", quality = 3, icon = "inv_staff_01"},
                    {id = 10711, name = "Dragon's Blood Necklace", slot = "Neck", quality = 3, icon = "inv_jewelry_necklace_02"},
                },
            },
            notes = "Spans three wings: Library, Armory and Cathedral. AtlasQuest gives minimum level 33; AzerothCore requires 30.",
            giver = "Varimathras",
            giverLocation = "Undercity - Royal Quarter (56.2, 92.6)",
            objective = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Varimathras in the Undercity.",
        },
    },
    preparation = {
        {
            title = "Level",
            lines = {"Wing level 36-42; entry from level 20 (Atlas)."},
        },
        {
            title = "Access & keys",
            lines = {
                "Scarlet Monastery is in north-eastern Tirisfal Glades; the four wings have separate instance portals (entrance map).",
                "The Scarlet Key drops from Doan's Strongbox after Arcanist Doan (Library [2]). It opens the Armory and Cathedral doors (AzerothCore lock 299 on both doors; Atlas lists the key for both wings).",
            },
        },
        {
            title = "Consumables",
            lines = {"Food, water and healing / mana potions."},
        },
        {
            title = "Server rules (restored Vanilla AI)",
            lines = {
                "Pulling Mograine brings every Scarlet monk, abbot, champion, centurion, wizard and chaplain within 80 yd.",
                "Abbots and Chaplains heal; Sorcerers cast Blizzard.",
                "Most Scarlet humanoids flee for help at 15% health: finish runners before they pull more.",
            },
        },
    },
})
