-- Scarlet Monastery: Graveyard (Vanilla batch 3, v0.3.3)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/SMGraveyard.blp, SMEnt.blp + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (SMGraveyard, SMTrash, WorldEvents HeadlessHorseman), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/dungeon_scarlet_monastery.sql smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    id = "smgy",
    name = "Scarlet Monastery: Graveyard",
    level = "28-35",
    location = "Tirisfal Glades",
    tag = "Dungeon",
    minLevel = "20",
    art = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenMonastery",
    crop = {0.04, 0.96, 0.29, 0.73},
    fallbackCrop = {0.0, 1.0, 0.25, 0.7},
    artFallback = SDJ.MAPS .. "SMGraveyard",
    maps = {
        {
            name = "SM: Graveyard",
            texture = SDJ.MAPS .. "SMGraveyard",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"1", "Interrogator Vishas"},
                {"", "Vorrel Sengutz"},
                {"2", "Pumpkin Shrine (Hallow's End)"},
                {"", "Headless Horseman (Summon)"},
                {"3", "Bloodmage Thalnos"},
                {"1'", "Ironspine (Rare)"},
                {"", "Azshir the Sleepless (Rare)"},
                {"", "Fallen Champion (Rare)"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
        {
            name = "Scarlet Monastery (Entrance)",
            texture = SDJ.MAPS .. "SMEnt",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"B", "Graveyard", "blue"},
                {"C", "Cathedral", "blue"},
                {"D", "Armory", "blue"},
                {"E", "Library", "blue"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
    },
    trash = {
        mobs = {
            {
                name = "Anguished Dead",
                npc = 6426,
                level = "31-33 Elite",
                priority = 1,
                abilities = {
                    {spell = 7068, name = "Veil of Shadow", tag = "DEBUFF", desc = "Healing received -75% for 15 sec (20 yd)."},
                },
                note = "Dispel Veil of Shadow from the tank.",
            },
            {
                name = "Scarlet Torturer",
                npc = 4306,
                level = "30-31 Elite",
                priority = 2,
                abilities = {
                    {spell = 9276, name = "Immolate", desc = "Has a 10% chance on hit to burn its target."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Scarlet Scryer",
                npc = 4293,
                level = "30-31 Elite",
                priority = 2,
                abilities = {
                    {spell = 9613, name = "Shadow Bolt", desc = "Shadow nuke, cast constantly."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Restored by Individual Progression: shares spawn points with the Scarlet Torturers.",
            },
            {
                name = "Haunting Phantasm",
                npc = 6427,
                level = "32-33 Elite",
                priority = 2,
                abilities = {
                    {spell = 8986, name = "Summon Illusionary Phantasm", tag = "SUMMON", desc = "Summons an Illusionary Phantasm for 1 min."},
                },
                note = "",
            },
            {
                name = "Scarlet Sentry",
                npc = 4283,
                level = "30-31 Elite",
                priority = 3,
                abilities = {
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "",
            },
            {
                name = "Unfettered Spirit",
                npc = 4308,
                level = "31-32",
                priority = 3,
                abilities = {},
                note = "Non-elite ghosts in the graveyard; no scripted abilities.",
            },
        },
        loot = {
            {id = 7728, name = "Beguiler Robes", slot = "Chest, Cloth", quality = 3, icon = "inv_chest_cloth_25", rate = "0.01%"},
            {id = 7755, name = "Flintrock Shoulders", slot = "Shoulder, Leather", quality = 3, icon = "inv_shoulder_13", rate = "0.00%"},
            {id = 7727, name = "Watchman Pauldrons", slot = "Shoulder, Leather", quality = 3, icon = "inv_shoulder_23", rate = "0.01%"},
            {id = 7760, name = "Warchief Kilt", slot = "Legs, Leather", quality = 3, icon = "inv_pants_06", rate = "0.00%"},
            {id = 7754, name = "Harbinger Boots", slot = "Feet, Leather", quality = 3, icon = "inv_boots_05", rate = "0.01%"},
            {id = 5819, name = "Sunblaze Coif", slot = "Head, Mail", quality = 3, icon = "inv_helmet_03", rate = "0.01%"},
            {id = 7759, name = "Archon Chestpiece", slot = "Chest, Mail", quality = 3, icon = "inv_chest_chain_11", rate = "0.00%"},
            {id = 10328, name = "Scarlet Chestpiece", slot = "Chest, Mail", quality = 3, icon = "inv_chest_chain_07", rate = "0.3%"},
            {id = 10332, name = "Scarlet Boots", slot = "Feet, Mail", quality = 3, icon = "inv_boots_02", rate = "0.1%"},
            {id = 2262, name = "Mark of Kern", slot = "Finger", quality = 3, icon = "inv_jewelry_ring_15", rate = "0.01%"},
            {id = 1992, name = "Swampchill Fetish", slot = "Held In Off-hand", quality = 3, icon = "inv_misc_bone_orcskull_01", rate = "0.00%"},
            {id = 10333, name = "Scarlet Wristguards", slot = "Wrist, Mail", quality = 2, icon = "inv_bracer_03", rate = "1.6%"},
            {id = 10331, name = "Scarlet Gauntlets", slot = "Hands, Mail", quality = 2, icon = "inv_gauntlets_19", rate = "1.7%"},
            {id = 10329, name = "Scarlet Belt", slot = "Waist, Mail", quality = 2, icon = "inv_belt_06", rate = "1.6%"},
            {id = 5756, name = "Sliverblade", slot = "One-Hand, Dagger", quality = 3, icon = "inv_weapon_shortblade_24", rate = "0.01%"},
            {id = 8225, name = "Tainted Pierce", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_30", rate = "0.01%"},
            {id = 8226, name = "The Butcher", slot = "One-Hand, Sword", quality = 3, icon = "inv_sword_18", rate = "0.01%"},
            {id = 7786, name = "Headsplitter", slot = "One-Hand, Axe", quality = 3, icon = "inv_axe_14", rate = "0.01%"},
            {id = 7761, name = "Steelclaw Reaver", slot = "One-Hand, Axe", quality = 3, icon = "inv_axe_06", rate = "0.01%"},
            {id = 7753, name = "Bloodspiller", slot = "Two-Hand, Axe", quality = 3, icon = "inv_axe_10", rate = "0.01%"},
            {id = 7752, name = "Dreamslayer", slot = "One-Hand, Mace", quality = 3, icon = "inv_hammer_17", rate = "0.01%"},
            {id = 7736, name = "Fight Club", slot = "One-Hand, Mace", quality = 3, icon = "inv_mace_11", rate = "0.00%"},
            {id = 7730, name = "Cobalt Crusher", slot = "Two-Hand, Mace", quality = 3, icon = "inv_hammer_04", rate = "0.01%"},
            {id = 7758, name = "Ruthless Shiv", slot = "Two-Hand, Polearm", quality = 3, icon = "inv_spear_08", rate = "0.00%"},
            {id = 7757, name = "Windweaver Staff", slot = "Two-Hand, Staff", quality = 3, icon = "inv_wand_07", rate = "0.01%"},
            {id = 7787, name = "Resplendent Guardian", slot = "Off Hand, Shield", quality = 3, icon = "inv_shield_02", rate = "0.01%"},
            {id = 7729, name = "Chesterfall Musket", slot = "Gun", quality = 3, icon = "inv_weapon_rifle_06", rate = "0.01%"},
            {
                id = 5805,
                name = "Heart of Zeal",
                slot = "Quest Item - Hearts of Zeal",
                quality = 1,
                icon = "inv_misc_organ_02",
                note = "Horde quest drop from Scarlet Monastery mobs (AzerothCore: 80% trash, 2% bosses).",
            },
        },
        lootNote = "AtlasLoot \"SMTrash\" is one shared table for all four Scarlet Monastery wings (rates as listed by AtlasLoot, some shown as 0.00%). Heart of Zeal comes from the AzerothCore loot tables.",
    },
    bosses = {
        {
            name = "Interrogator Vishas",
            npc = 3983,
            level = "32 Elite",
            portrait = P .. "InterrogatorVishas",
            summary = "Scarlet interrogator in the torture room [1], near the prisoner Vorrel Sengutz.",
            abilities = {
                {spell = 2767, name = "Shadow Word: Pain", tag = "DOT", desc = "Shadow damage over time on a random target."},
            },
            mechanics = {"Tank-and-spank; dispel Shadow Word: Pain."},
            loot = {
                {id = 7683, name = "Bloody Brass Knuckles", slot = "One-Hand, Fist Weapon", quality = 3, icon = "inv_gauntlets_11", rate = "66.1%"},
                {id = 7682, name = "Torturing Poker", slot = "One-Hand, Dagger", quality = 3, icon = "inv_spear_01", rate = "5.56%"},
            },
        },
        {
            name = "Bloodmage Thalnos",
            npc = 4543,
            level = "34 Elite",
            portrait = P .. "BloodmageThalnos",
            summary = "Undead caster at the end of the wing [3].",
            abilities = {
                {spell = 9613, name = "Shadow Bolt", desc = "Shadow nuke."},
                {spell = 8814, name = "Flame Spike", tag = "AOE", desc = "Fire pillar on a target area (30 yd)."},
                {spell = 8053, name = "Flame Shock", desc = "Fire damage plus a burn (20 yd)."},
                {spell = 12470, name = "Fire Nova", tag = "AOE", desc = "Fire damage to nearby enemies."},
            },
            mechanics = {
                "Melee spread for Fire Nova; move out of Flame Spike.",
                "Interrupt Shadow Bolt.",
            },
            loot = {
                {id = 7684, name = "Bloodmage Mantle", slot = "Shoulder, Cloth", quality = 3, icon = "inv_shoulder_05", rate = "48.46%"},
                {id = 7685, name = "Orb of the Forgotten Seer", slot = "Held In Off-hand", quality = 3, icon = "inv_misc_orb_02", rate = "47.07%"},
            },
        },
        {
            name = "Ironspine",
            npc = 6489,
            level = "33 Rare Elite",
            optional = true,
            rare = true,
            portrait = P .. "Ironspine",
            summary = "Rare skeleton [1']. Individual Progression gives it a 10% spawn chance.",
            abilities = {
                {spell = 21007, name = "Curse of Weakness", tag = "CURSE", desc = "On aggro: nearby players deal less physical damage."},
                {spell = 3815, name = "Poison Cloud", tag = "AOE", desc = "Nature damage over 45 sec to players within 8 yd."},
            },
            mechanics = {"Decurse; ranged stay out of 8 yd."},
            loot = {
                {id = 7688, name = "Ironspine's Ribcage", slot = "Chest, Mail", quality = 3, icon = "inv_chest_plate15", rate = "32.91%"},
                {id = 7686, name = "Ironspine's Eye", slot = "Finger", quality = 3, icon = "inv_jewelry_ring_04", rate = "40.08%"},
                {id = 7687, name = "Ironspine's Fist", slot = "One-Hand, Mace", quality = 3, icon = "inv_hammer_19", rate = "20.34%"},
            },
        },
        {
            name = "Azshir the Sleepless",
            npc = 6490,
            level = "33 Rare Elite",
            optional = true,
            rare = true,
            portrait = P .. "AzshirTheSleepless",
            summary = "Rare undead [1']; 10% spawn chance.",
            abilities = {
                {spell = 5137, name = "Call of the Grave", tag = "DOT", desc = "Shadow damage after 60 sec."},
                {spell = 7399, name = "Terrify", tag = "FEAR", desc = "Fears the tank for 4 sec."},
                {spell = 9373, name = "Soul Siphon", desc = "Below 50%: drains health from players and nearby allies."},
                {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
            },
            mechanics = {"Off-tank ready for Terrify."},
            loot = {
                {id = 7709, name = "Blighted Leggings", slot = "Legs, Cloth", quality = 3, icon = "inv_pants_07", rate = "31.19%"},
                {id = 7731, name = "Ghostshard Talisman", slot = "Neck", quality = 3, icon = "inv_jewelry_necklace_06", rate = "32.71%"},
                {id = 7708, name = "Necrotic Wand", slot = "Ranged, Wand", quality = 3, icon = "inv_wand_04", rate = "30.72%"},
            },
        },
        {
            name = "Fallen Champion",
            npc = 6488,
            level = "33 Rare Elite",
            optional = true,
            rare = true,
            portrait = P .. "FallenChampion",
            summary = "Rare undead warrior [1']; 10% spawn chance.",
            abilities = {
                {spell = 15496, name = "Cleave", desc = "Hits the target and the nearest ally."},
                {spell = 7160, name = "Execute", desc = "Heavy hit on a target below 20% health."},
            },
            mechanics = {"Only the tank in front; keep the tank topped up."},
            loot = {
                {id = 7691, name = "Embalmed Shroud", slot = "Head, Cloth", quality = 3, icon = "inv_helmet_28", rate = "38.58%"},
                {id = 7690, name = "Ebon Vise", slot = "Hands, Leather", quality = 3, icon = "inv_gauntlets_32", rate = "37.83%"},
                {id = 7689, name = "Morbid Dawn", slot = "Two-Hand, Sword", quality = 3, icon = "inv_sword_12", rate = "19.15%"},
            },
        },
        {
            name = "Headless Horseman",
            npc = 23682,
            level = "80 Elite",
            optional = true,
            portrait = P .. "HeadlessHorseman",
            summary = "Hallow's End only: summoned at the Pumpkin Shrine [2]. Once per instance (AzerothCore).",
            abilities = {
                {spell = 42587, name = "Horseman's Cleave", desc = "Hits the target and nearby allies."},
                {
                    spell = 43116,
                    name = "Headless Horseman Climax - Horseman's Whirlwind",
                    tag = "AOE",
                    desc = "While headless, his body regenerates and whirlwinds (no tooltip description in the 3.3.5 data).",
                },
                {spell = 42380, name = "Conflagration", tag = "FEAR", desc = "Phase 2+: fire on a random target, who panics."},
                {
                    spell = 42552,
                    name = "Summon Pumpkin Missile",
                    tag = "SUMMON",
                    desc = "Phase 3: sprouts pumpkins that become Pumpkin Fiends (no tooltip description in the 3.3.5 data).",
                },
            },
            mechanics = {
                "When the body reaches zero health it throws its head: kill the head while the body regenerates.",
                "Three phases: phase 2 adds Conflagration, phase 3 adds Sprouting Pumpkins.",
                "Seasonal boss from AzerothCore hallows_end.cpp; not part of the normal run.",
            },
            loot = {
                {id = 49126, name = "The Horseman's Horrific Helm", slot = "Head, Plate", quality = 4, icon = "inv_helmet_21"},
                {id = 49121, name = "Ring of Ghoulish Glee", slot = "Finger", quality = 4, icon = "inv_misc_bag_28_halloween"},
                {id = 49123, name = "The Horseman's Seal", slot = "Finger", quality = 4, icon = "inv_misc_bag_28_halloween"},
                {id = 49124, name = "Wicked Witch's Band", slot = "Finger", quality = 4, icon = "inv_misc_bag_28_halloween"},
                {id = 49128, name = "The Horseman's Baleful Blade", slot = "Main Hand, Sword", quality = 4, icon = "inv_sword_07"},
                {id = 34068, name = "Weighted Jack-o'-Lantern", slot = "Item", quality = 1, icon = "inv_misc_bag_28_halloween", rate = "100%"},
                {id = 33226, name = "Tricky Treat", slot = "Item", quality = 1, icon = "inv_misc_food_25"},
                {id = 37012, name = "The Horseman's Reins", slot = "Item", quality = 4, icon = "inv_belt_12"},
                {id = 37011, name = "Magic Broom", slot = "Item", quality = 3, icon = "achievement_halloween_witch_01"},
                {id = 33292, name = "Hallowed Helm", slot = "Head, Cloth", quality = 3, icon = "inv_misc_bag_28_halloween"},
                {id = 33154, name = "Sinister Squashling", slot = "Companion", quality = 3, icon = "inv_misc_food_59"},
            },
            lootNote = "AtlasLoot World Events \"Headless Horseman\"; only the Weighted Jack-o'-Lantern has a listed rate.",
        },
    },
    quests = {
        {
            id = 1051,
            name = "Vorrel's Revenge",
            faction = "Horde",
            level = 33,
            minLevel = 25,
            prerequisites = "None.",
            requiredItems = {
                {id = 5538, name = "Vorrel's Wedding Ring", where = "Nancy Vishas, in a house in Alterac Mountains near (31, 32); the house can vary"},
            },
            turnin = "Monika Sengutz",
            turninLocation = "Hillsbrad Foothills - Tarren Mill (62.6, 19.0)",
            rewards = {
                reputation = "Undercity",
                choice = {
                    {id = 7750, name = "Mantle of Woe", slot = "Shoulder, Cloth", quality = 2, icon = "inv_shoulder_23"},
                    {id = 4643, name = "Grimsteel Cape", slot = "Back", quality = 2, icon = "inv_misc_cape_02"},
                },
                items = {
                    {id = 7751, name = "Vorrel's Boots", slot = "Feet, Leather", quality = 2, icon = "inv_boots_03"},
                },
            },
            giver = "Vorrel Sengutz",
            giverLocation = "Scarlet Monastery - Graveyard [1]",
            objective = "Return Vorrel Sengutz's wedding ring to Monika Sengutz in Tarren Mill.",
        },
        {
            id = 1113,
            name = "Hearts of Zeal",
            faction = "Horde",
            level = 33,
            minLevel = 30,
            prerequisites = "Going, Going, Guano! (1109, Razorfen Kraul).",
            requiredItems = {
                {id = 5805, name = "Heart of Zeal", where = "Any Scarlet Monastery mob, including those outside near the portals (x20)"},
            },
            turnin = "Master Apothecary Faranell",
            turninLocation = "Undercity - The Apothecarium (48.6, 69.4)",
            rewards = {reputation = "Undercity"},
            notes = "Hearts of Zeal drop in every wing.",
            giver = "Master Apothecary Faranell",
            giverLocation = "Undercity - The Apothecarium (48.6, 69.4)",
            objective = "Master Apothecary Faranell in the Undercity wants 20 Hearts of Zeal.",
        },
    },
    preparation = {
        {
            title = "Level",
            lines = {"Wing level 28-35; entry from level 20 (Atlas)."},
        },
        {
            title = "Access & keys",
            lines = {
                "Scarlet Monastery is in north-eastern Tirisfal Glades; the four wings have separate instance portals (entrance map).",
                "No key needed for the Graveyard.",
                "Hallow's End: the Pumpkin Shrine [2] summons the Headless Horseman.",
            },
        },
        {
            title = "Consumables",
            lines = {"Food, water and healing / mana potions."},
        },
        {
            title = "Server rules (restored Vanilla AI)",
            lines = {
                "Anguished Dead cut healing taken by 75%.",
                "Individual Progression restores Scarlet Scryers and gives each rare 10% spawn chance.",
                "Most Scarlet humanoids flee for help at 15% health: finish runners before they pull more.",
            },
        },
    },
})
