-- The Stockade (Vanilla batch 2, v0.3.2)
--
-- Sources (see CREDITS.txt for full credits / licences):
--  * Map(s) + legend: Atlas 1.17.0 for 3.3.5 (Dan Gilbert; map art by Niflheim), GPLv2,
--    TrinityCore/wow_335a_addons Atlas/Atlas/Images/Maps/TheStockade.blp + AtlasMaps.lua
--  * Boss / trash loot + drop %: AtlasLoot_OriginalWoW/originalwow.lua (TheStockade), GPL
--  * Quests: AtlasQuest (nanderson11/AtlasQuest, GPLv2), cross-checked with the AzerothCore
--    world DB (quest_template, quest_template_addon, creature_queststarter/questender,
--    creature_loot_template) for IDs, levels, chain order and rewards.
--  * Creature abilities: mod-individual-progression data/sql/world/base/dungeon_stockade.sql smart_scripts
--    (restored Vanilla AI) where present, otherwise AzerothCore smart_scripts / C++ scripts.
--    Spell names/descriptions: Wowhead WotLK tooltips of the scripted spell IDs.
--  * Creature levels / elite rank / spawn chance: AzerothCore creature_template + smart_scripts.
-- No drop rate is invented: an item without a recorded rate has rate = nil.
-- GENERATED by tools/gen (source data in /workspace/sdj/src/extract); edit the generator.
local SDJ = DungeonJournal
local P = SDJ.PORTRAITS

SDJ:AddDungeon("Vanilla", {
    id = "stockade",
    name = "The Stockade",
    level = "21-27",
    minLevel = "15",
    location = "Stormwind City",
    tag = "Dungeon",
    art = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenStormwindStockade",
    artFallback = SDJ.MAPS .. "TheStockade",
    crop = {0.04, 0.96, 0.29, 0.73},
    fallbackCrop = {0.0, 1.0, 0.25, 0.7},
    maps = {
        {
            name = "The Stockade",
            texture = SDJ.MAPS .. "TheStockade",
            coords = {0, 1, 0, 1},
            legend = {
                {"A", "Entrance", "blue"},
                {"1", "Targorr the Dread (Varies)"},
                {"2", "Kam Deepfury"},
                {"3", "Hamhock"},
                {"4", "Bazil Thredd"},
                {"5", "Dextren Ward"},
                {"6", "Bruegal Ironknuckle (Rare)"},
            },
            credit = "Map: Atlas (Dan Gilbert, map by Niflheim) - GPL",
        },
    },
    trash = {
        mobs = {
            {
                name = "Defias Insurgent",
                npc = 1715,
                level = "25-26 Elite",
                priority = 1,
                abilities = {
                    {spell = 9128, name = "Battle Shout", tag = "BUFF", desc = "Raises nearby allies' melee attack power for 2 min."},
                    {spell = 13730, name = "Demoralizing Shout", tag = "DEBUFF", desc = "Lowers nearby enemies' melee attack power for 30 sec."},
                    {spell = 6253, name = "Backhand", tag = "STUN", desc = "Stuns the target for 2 sec."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Kill first in mixed packs (buffs the others). Quell The Uprising target.",
            },
            {
                name = "Defias Captive",
                npc = 1707,
                level = "23-24 Elite",
                priority = 1,
                abilities = {
                    {spell = 7159, name = "Backstab", desc = "Bonus damage from behind."},
                    {spell = 3427, name = "Infected Wound", tag = "DEBUFF", desc = "Target takes more physical damage for 30 sec."},
                    {spell = 11977, name = "Rend", desc = "Physical DoT for 15 sec."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Keep it facing the tank; healers watch the Infected Wound target.",
            },
            {
                name = "Defias Convict",
                npc = 1711,
                level = "24-25 Elite",
                priority = 2,
                abilities = {
                    {spell = 674, name = "Dual Wield", desc = "Dual wields."},
                    {spell = 6253, name = "Backhand", tag = "STUN", desc = "Stuns the target for 2 sec."},
                    {spell = 11977, name = "Rend", desc = "Physical DoT for 15 sec."},
                    {spell = 13730, name = "Demoralizing Shout", tag = "DEBUFF", desc = "Lowers nearby enemies' melee attack power."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Quell The Uprising target.",
            },
            {
                name = "Defias Prisoner",
                npc = 1706,
                level = "23-24 Elite",
                priority = 2,
                abilities = {
                    {spell = 1766, name = "Kick", tag = "INTERRUPT", desc = "Interrupts spellcasting."},
                    {spell = 6713, name = "Disarm", tag = "DISARM", desc = "Disarms for 6 sec."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Kicks healers' casts; Quell The Uprising target.",
            },
            {
                name = "Defias Inmate",
                npc = 1708,
                level = "24-25 Elite",
                priority = 3,
                abilities = {
                    {spell = 11977, name = "Rend", desc = "Physical DoT for 15 sec."},
                    {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
                },
                note = "Most common mob.",
            },
        },
        loot = {
            {
                id = 2909,
                name = "Red Wool Bandana",
                slot = "Quest Item - The Color of Blood",
                quality = 1,
                icon = "inv_misc_bandana_03",
                note = "AtlasLoot lists it for trash (no %). AzerothCore: 80% quest drop from all Defias inmates, 40% from Dextren Ward.",
            },
        },
        lootNote = "AtlasLoot has only the Red Wool Bandana (quest item) for Stockade trash.",
    },
    bosses = {
        {
            name = "Targorr the Dread",
            npc = 1696,
            level = "24 Elite",
            portrait = P .. "TargorrTheDread",
            summary = "Orc prisoner [1] (position varies). His head is needed for What Comes Around...",
            abilities = {
                {spell = 674, name = "Dual Wield", desc = "Dual wields."},
                {spell = 3391, name = "Thrash", desc = "Two extra attacks every 15-20 sec."},
                {spell = 3417, name = "Thrash", desc = "Passive: chance for two extra attacks."},
                {spell = 8599, name = "Enrage", tag = "ENRAGE", desc = "Below 30%: more damage and attack speed for 2 min."},
            },
            mechanics = {"Tank cooldowns when he enrages at 30%."},
            loot = {
                {id = 3630, name = "Head of Targorr", slot = "Quest Item - What Comes Around...", quality = 1, icon = "inv_misc_head_orc_01", rate = "100%"},
            },
        },
        {
            name = "Kam Deepfury",
            npc = 1666,
            level = "27 Elite",
            portrait = P .. "KamDeepfury",
            summary = "Dark Iron dwarf [2]. His head is needed for The Fury Runs Deep.",
            abilities = {
                {spell = 7164, name = "Defensive Stance", desc = "Defensive stance."},
                {spell = 8242, name = "Shield Slam", tag = "STUN", desc = "Damage plus 2 sec stun."},
                {spell = 3419, name = "Improved Blocking", desc = "Block chance +75% for 6 sec."},
                {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
            },
            mechanics = {"Slow but durable fight. Stop him fleeing at 15%."},
            loot = {
                {id = 2280, name = "Kam's Walking Stick", slot = "Two-Hand, Staff", quality = 3, icon = "inv_staff_06", rate = "0.62%"},
                {id = 3640, name = "Head of Deepfury", slot = "Quest Item - The Fury Runs Deep", quality = 1, icon = "inv_misc_head_dwarf_01", rate = "100%"},
            },
        },
        {
            name = "Hamhock",
            npc = 1717,
            level = "28 Elite",
            portrait = P .. "Hamhock",
            summary = "Ogre prisoner [3].",
            abilities = {
                {spell = 421, name = "Chain Lightning", tag = "AOE", desc = "Lightning that jumps to nearby enemies."},
                {spell = 6742, name = "Bloodlust", tag = "BUFF", desc = "Attack speed +30% for 30 sec."},
            },
            mechanics = {
                "Spread out against Chain Lightning.",
                "Interrupt Chain Lightning where possible.",
            },
            loot = {},
            lootNote = "No Hamhock table in AtlasLoot 3.3.5.",
        },
        {
            name = "Bazil Thredd",
            npc = 1716,
            level = "29 Elite",
            portrait = P .. "BazilThredd",
            summary = "Defias leader of the riot [4]. Kill target for The Stockade Riots.",
            abilities = {
                {spell = 674, name = "Dual Wield", desc = "Dual wields."},
                {spell = 7964, name = "Smoke Bomb", tag = "STUN", desc = "Stuns nearby enemies for 4 sec."},
                {spell = 9128, name = "Battle Shout", tag = "BUFF", desc = "Raises nearby allies' melee attack power."},
                {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
            },
            mechanics = {
                "Healers top everyone up before Smoke Bomb stuns.",
                "Stop him fleeing at 15%.",
            },
            loot = {
                {id = 2926, name = "Head of Bazil Thredd", slot = "Quest Item - The Stockade Riots", quality = 1, icon = "inv_misc_head_human_01", rate = "100%"},
            },
        },
        {
            name = "Dextren Ward",
            npc = 1663,
            level = "26 Elite",
            portrait = P .. "DextrenWard",
            summary = "Human murderer [5]. His hand is needed for Crime and Punishment.",
            abilities = {
                {spell = 19134, name = "Frightening Shout", tag = "FEAR", desc = "Fears nearby enemies for 8 sec (10 yd)."},
                {spell = 11976, name = "Strike", desc = "Weapon damage plus extra damage."},
                {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
            },
            mechanics = {
                "Fears everyone within 10 yd: ranged and healers stay back; use fear protection if you have it.",
                "Clear nearby cells so feared players do not pull more.",
            },
            loot = {
                {id = 3628, name = "Hand of Dextren Ward", slot = "Quest Item - Crime and Punishment", quality = 1, icon = "inv_gauntlets_09", rate = "100%"},
            },
        },
        {
            name = "Bruegal Ironknuckle",
            npc = 1720,
            level = "26 Rare Elite",
            optional = true,
            rare = true,
            portrait = P .. "BruegalIronknuckle",
            summary = "Rare dwarf [6]. On this server he spawns about 30% of the time (70% despawn chance).",
            abilities = {
                {name = "Flees for help", tag = "FLEE", desc = "Runs at 15% health."},
            },
            mechanics = {"No combat spells in the server script; stop him fleeing."},
            loot = {
                {id = 3228, name = "Jimmied Handcuffs", slot = "Wrist, Mail", quality = 3, icon = "inv_bracer_02", rate = "54.73%"},
                {id = 2942, name = "Iron Knuckles", slot = "One-Hand, Fist Weapon", quality = 3, icon = "inv_gauntlets_04", rate = "18.18%"},
                {id = 2941, name = "Prison Shank", slot = "One-Hand, Dagger", quality = 3, icon = "inv_weapon_shortblade_18", rate = "16.05%"},
            },
        },
    },
    quests = {
        {
            id = 386,
            name = "What Comes Around...",
            faction = "Alliance",
            level = 25,
            minLevel = 22,
            giver = "Guard Berton",
            giverLocation = "Redridge Mountains - Lakeshire (26.4, 46.6)",
            prerequisites = "None.",
            objective = "Bring the head of Targorr the Dread to Guard Berton in Lakeshire.",
            requiredItems = {
                {id = 3630, name = "Head of Targorr", where = "Targorr the Dread [1]"},
            },
            turnin = "Guard Berton",
            turninLocation = "Redridge Mountains - Lakeshire (26.4, 46.6)",
            rewards = {
                reputation = "Stormwind",
                choice = {
                    {id = 3400, name = "Lucine Longsword", slot = "One-Hand, Sword", quality = 2, icon = "inv_sword_20"},
                    {id = 1317, name = "Hardened Root Staff", slot = "Two-Hand, Staff", quality = 2, icon = "inv_staff_16"},
                },
            },
        },
        {
            id = 377,
            name = "Crime and Punishment",
            faction = "Alliance",
            level = 26,
            minLevel = 22,
            giver = "Councilman Millstipe",
            giverLocation = "Duskwood - Darkshire (72.0, 47.8)",
            prerequisites = "None.",
            objective = "Councilman Millstipe of Darkshire wants you to bring him the hand of Dextren Ward.",
            requiredItems = {
                {id = 3628, name = "Hand of Dextren Ward", where = "Dextren Ward [5]"},
            },
            turnin = "Councilman Millstipe",
            turninLocation = "Duskwood - Darkshire (72.0, 47.8)",
            rewards = {
                reputation = "Stormwind",
                choice = {
                    {id = 2033, name = "Ambassador's Boots", slot = "Feet, Leather", quality = 2, icon = "inv_boots_08"},
                    {id = 2906, name = "Darkshire Mail Leggings", slot = "Legs, Mail", quality = 2, icon = "inv_pants_03"},
                },
            },
        },
        {
            id = 387,
            name = "Quell The Uprising",
            faction = "Alliance",
            level = 26,
            minLevel = 22,
            giver = "Warden Thelwater",
            giverLocation = "Stormwind - The Stockade entrance (41.2, 58.0)",
            prerequisites = "None.",
            objective = "Warden Thelwater of Stormwind wants you to kill 10 Defias Prisoners, 8 Defias Convicts, and 8 Defias Insurgents in The Stockade.",
            turnin = "Warden Thelwater",
            turninLocation = "Stormwind - The Stockade entrance (41.2, 58.0)",
            rewards = {money = 6000, reputation = "Stormwind"},
            notes = "You may have to wait for respawns to finish the counts.",
        },
        {
            id = 388,
            name = "The Color of Blood",
            faction = "Alliance",
            level = 26,
            minLevel = 22,
            giver = "Nikova Raskol",
            giverLocation = "Stormwind - Old Town (66.8, 46.4)",
            prerequisites = "None.",
            objective = "Nikova Raskol of Stormwind wants you to collect 10 Red Wool Bandanas.",
            requiredItems = {
                {id = 2909, name = "Red Wool Bandana", where = "All Defias inside the dungeon"},
            },
            turnin = "Nikova Raskol",
            turninLocation = "Stormwind - Old Town (66.8, 46.4)",
            rewards = {money = 6000, reputation = "Stormwind"},
            notes = "Nikova Raskol walks around Old Town.",
        },
        {
            id = 378,
            name = "The Fury Runs Deep",
            faction = "Alliance",
            level = 27,
            minLevel = 22,
            giver = "Motley Garmason",
            giverLocation = "Wetlands - Dun Modr (49.6, 18.2)",
            prerequisites = "The Dark Iron War (303) from Motley Garmason.",
            objective = "Motley Garmason wants Kam Deepfury's head brought to him at Dun Modr.",
            requiredItems = {
                {id = 3640, name = "Head of Deepfury", where = "Kam Deepfury [2]"},
            },
            turnin = "Motley Garmason",
            turninLocation = "Wetlands - Dun Modr (49.6, 18.2)",
            chain = {
                {id = 303, name = "The Dark Iron War", text = "Motley Garmason: kill Dark Iron dwarves at Dun Modr."},
                {id = 378, name = "The Fury Runs Deep", text = "Bring Kam Deepfury's head. (this quest)"},
            },
            rewards = {
                reputation = "Ironforge",
                choice = {
                    {id = 3562, name = "Belt of Vindication", slot = "Waist, Leather", quality = 2, icon = "inv_belt_05"},
                    {id = 1264, name = "Headbasher", slot = "Two-Hand, Mace", quality = 2, icon = "inv_mace_07"},
                },
            },
        },
        {
            id = 391,
            name = "The Stockade Riots",
            faction = "Alliance",
            level = 29,
            minLevel = 16,
            giver = "Warden Thelwater",
            giverLocation = "Stormwind - The Stockade entrance (41.2, 58.0)",
            prerequisites = "The Unsent Letter (373, from VanCleef in The Deadmines) and Bazil Thredd (389).",
            objective = "Kill Bazil Thredd and bring his head back to Warden Thelwater at the Stockade.",
            requiredItems = {
                {id = 2926, name = "Head of Bazil Thredd", where = "Bazil Thredd [4]"},
            },
            turnin = "Warden Thelwater",
            turninLocation = "Stormwind - The Stockade entrance (41.2, 58.0)",
            followUp = "The Curious Visitor (392)",
            chain = {
                {id = 373, name = "The Unsent Letter", text = "An Unsent Letter (VanCleef, Deadmines) -> Baros Alexston."},
                {id = 389, name = "Bazil Thredd", text = "Speak with Warden Thelwater."},
                {id = 391, name = "The Stockade Riots", text = "Kill Bazil Thredd, bring his head. (this quest)"},
                {id = 392, name = "The Curious Visitor", text = "Warden Thelwater -> Baros Alexston."},
                {id = 393, name = "Shadow of the Past", text = "Baros Alexston -> Master Mathias Shaw."},
                {id = 350, name = "Look to an Old Friend", text = "Speak to Elling Trias."},
                {id = 2745, name = "Infiltrating the Castle", text = "Speak to Tyrion in Stormwind Castle."},
                {id = 2746, name = "Items of Some Consequence", text = "3 Silk Cloth and 2 Clara's Fresh Apple for Tyrion."},
                {id = 434, name = "The Attack!", text = "Kill Lord Gregor Lescovar and Marzon the Silent Blade."},
                {id = 394, name = "The Head of the Beast", text = "Speak to Mathias Shaw."},
                {id = 395, name = "Brotherhood's End", text = "Speak with Baros Alexston."},
                {id = 396, name = "An Audience with the King", text = "Report to the King. Reward: Seal of Wrynn."},
            },
            rewards = {money = 2500, reputation = "Stormwind"},
            notes = "Quest level 29 (AzerothCore); part of the long Defias chain.",
        },
    },
    preparation = {
        {
            title = "Level",
            lines = {"Dungeon level 21-27; entry from level 15 (Atlas)."},
        },
        {
            title = "Consumables",
            lines = {
                "Food, water and healing / mana potions.",
                "Fear protection helps against Dextren Ward.",
            },
        },
        {
            title = "Keys & required items",
            lines = {
                "No key. Entrance: Stormwind City (Warden Thelwater stands outside).",
                "Horde has no Stockade quests in AtlasQuest.",
            },
        },
        {
            title = "Server rules (restored Vanilla AI)",
            lines = {
                "Nearly every Defias flees at 15% health - finish runners before they chain pulls.",
                "Defias Prisoners kick casts; Insurgents buff their pack.",
            },
        },
    },
})
